"""Twenty distinct, metric-scale multi-building indoor/outdoor assemblies."""
SCENES = [
    (
        "dining_courtyard",
        "restaurant · coffee shop · fresh market courtyard",
        "restaurant",
        ["cafe", "market"],
        "courtyard",
        [],
    ),
    (
        "coffee_corner",
        "Coffee House · Residential · Corner of Restaurant",
        "cafe",
        ["townhouse", "restaurant"],
        "corner",
        ["parcel"],
    ),
    (
        "market_lane",
        "Fresh Market · Pharmacy · Coffee Street Lane",
        "market",
        ["pharmacy", "cafe"],
        "staggered",
        ["food_locker"],
    ),
    (
        "medical_court",
        "Community Hospital · Pharmacy · Coffee Shop",
        "hospital",
        ["pharmacy", "cafe"],
        "forecourt",
        [],
    ),
    (
        "pharmacy_square",
        "pharmacy · residential · fresh neighborhood square",
        "pharmacy",
        ["townhouse", "market"],
        "offset_square",
        ["atm"],
    ),
    (
        "reading_court",
        "Library · Coffee Shop · Teaching Building",
        "library",
        ["cafe", "school"],
        "courtyard",
        [],
    ),
    ("campus_lane", "school · gym · coffee alley", "cafe", ["school", "gym"], "campus", ["bike"]),
    (
        "sports_plaza",
        "Sports Center · Restaurant · Fast Food Plaza",
        "restaurant",
        ["gym", "fastfood"],
        "corner",
        ["fitness", "fitness_walk"],
    ),
    (
        "residential_mews",
        "Neighborhood Housing Complex · Community Fresh Market",
        "market",
        ["townhouse", "townhouse", "cafe"],
        "mews",
        ["parcel"],
    ),
    (
        "garden_homes",
        "Garden Home · Coffee Shop · Pharmacy",
        "cafe",
        ["townhouse", "pharmacy"],
        "garden",
        ["food_locker"],
    ),
    (
        "civic_corner",
        "Police Bureau · Restaurant · Corner of Coffee Street",
        "restaurant",
        ["police", "cafe"],
        "forecourt",
        ["atm"],
    ),
    (
        "fire_service_lane",
        "fire station · supermarket · courier center",
        "market",
        ["fire", "delivery"],
        "service",
        ["parcel"],
    ),
    (
        "bank_square",
        "Bank · Coffee House · Pharmacy Square",
        "cafe",
        ["bank", "pharmacy"],
        "offset_square",
        ["atm"],
    ),
    (
        "factory_court",
        "factory · restaurant · post office",
        "restaurant",
        ["factory", "delivery"],
        "service",
        ["food_locker"],
    ),
    (
        "roadside_services",
        "gas station · supermarket · coffee shop",
        "market",
        ["gas", "cafe"],
        "staggered",
        ["atm"],
    ),
    (
        "lakeside_reading",
        "Lakeside Café & Library",
        "cafe",
        ["library", "bar"],
        "waterside",
        ["lake"],
    ),
    (
        "waterside_dining",
        "River & Bridge Restaurant & Coffee House & Residential Property",
        "restaurant",
        ["cafe", "townhouse"],
        "waterside",
        ["river"],
    ),
    (
        "health_promenade",
        "Pharmacy · Hospital · Residential Street",
        "pharmacy",
        ["hospital", "townhouse"],
        "promenade",
        [],
    ),
    (
        "parcel_neighborhood",
        "Post office · Coffee shop · Supermarket",
        "cafe",
        ["delivery", "market"],
        "mews",
        ["parcel", "food_locker"],
    ),
    (
        "community_reading_park",
        "Community Park · Library · Residential Area · Coffee Shop",
        "library",
        ["townhouse", "cafe"],
        "garden",
        ["fitness", "fitness_walk"],
    ),
]
