# Allow direct execution as well as package imports.
import sys as _wb_sys
from pathlib import Path as _WBPath

_wb_root = next(
    p for p in _WBPath(__file__).resolve().parents if (p / "worldbridge").is_dir()
)
if str(_wb_root) not in _wb_sys.path:
    _wb_sys.path.insert(0, str(_wb_root))
from worldbridge.paths import path_variables as _wb_path_variables

_wb_paths = _wb_path_variables()

_wb_WORLDBRIDGE_ROOT = _wb_paths["WORLDBRIDGE_ROOT"]
_wb_WORLDBRIDGE_EXTERNAL = _wb_paths["WORLDBRIDGE_EXTERNAL"]
_wb_WORLDBRIDGE_SITE_PACKAGES = _wb_paths["WORLDBRIDGE_SITE_PACKAGES"]

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from worldbridge.llm_config import (
    complete_text,
    describe_llm_exception,
    get_llm_config,
    make_openai_client,
)

INPUT_MANIFEST = Path("./output/urban/manifest_scene_urban.json")
INPUT_PARAMS = Path("./output/urban/urban_params.json")
REF_BASE_GIN = Path("./infinigen/infinigen_examples/configs_urban/base_urban.gin")

OUTPUT_GIN = Path(
    "./infinigen/infinigen_examples/configs_urban/generated_urban_scene.gin"
)
OUTPUT_GIN_COPY = Path("./output/urban/generated_urban_scene.gin")
OUTPUT_RUN_ARGS = Path("./output/urban/urban_run_args.json")
OUTPUT_SCENE_PY = Path("./output/urban/urban_scene.py")

# Gin param sets (flat/legacy path only)
_COMPOSE_URBAN_PARAMS = {
    "compose_urban.block_extent",
    "compose_urban.road_width",
    "compose_urban.sidewalk_width",
    "compose_urban.curb_height",
    "compose_urban.min_building_height",
    "compose_urban.max_building_height",
}
_OUTDOOR_ASSETS_PARAMS = {
    "_outdoor_assets.n_street_lamps",
    "_outdoor_assets.has_bus_stop",
    "_outdoor_assets.n_bike_racks",
    "_outdoor_assets.has_fire_hydrant",
    "_outdoor_assets.n_trees",
    "_outdoor_assets.tree_season",
    "_outdoor_assets.n_grass_tufts",
    "_outdoor_assets.n_shrubs",
    "_outdoor_assets.n_flower_plants",
    "_outdoor_assets.has_fountain",
    "_outdoor_assets.has_sculpture",
    "_outdoor_assets.n_planters",
    "_outdoor_assets.n_vehicles",
    "_outdoor_assets.n_pedestrians",
    "_outdoor_assets.n_benches",
    "_outdoor_assets.n_trash_bins",
    "_outdoor_assets.has_traffic_lights",
    "_outdoor_assets.has_traffic_signs",
}
_RENDER_PARAMS = {
    "configure_render_cycles.exposure",
    "configure_render_cycles.num_samples",
    "nishita_lighting.sun_elevation",
}


# ─── FLAT GIN BUILDER (legacy path) ──────────────────────────────────────────
def _fmt(value):
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value}"
    return str(value)


def build_gin_from_params(params, manifest_data=None):
    lines = ["# Generated by Urban Realizer (WorldBridge)"]
    lines.append("\n# Block layout")
    for key in sorted(_COMPOSE_URBAN_PARAMS):
        if key in params:
            lines.append(f"{key} = {_fmt(params[key])}")
    lines.append("\n# Outdoor asset controls")
    for key in sorted(_OUTDOOR_ASSETS_PARAMS):
        if key in params:
            lines.append(f"{key} = {_fmt(params[key])}")
    lines.append("\n# Render and lighting")
    for key in sorted(_RENDER_PARAMS):
        if key in params:
            lines.append(f"{key} = {_fmt(params[key])}")
    if "atmosphere.fog_density" in params:
        fog = params["atmosphere.fog_density"]
        lines.append("\n# Atmosphere")
        lines.append(f"shader_atmosphere.density = {_fmt(fog)}")
        if fog > 0.005:
            lines.append("nishita_lighting.dust_density = 0.0")
    return "\n".join(lines)


# ─── CROSSROADS BLENDER SCRIPT BUILDER ───────────────────────────────────────
def build_crossroads_script(params):
    """
    Generate an executable Blender Python script from crossroads_4zone params.
    The script is self-contained and uses urban_assets.py.
    """
    p = params
    g = p.get("geometry", {})
    R = g.get("R", 4.5)
    SW = g.get("SW", 3.5)
    FW = g.get("FW", 2.5)
    ARM = g.get("ARM", 50.0)
    S1 = g.get("S1", R + SW)
    G1 = g.get("G1", R + SW + FW)
    LC = g.get("LC", R / 2)

    rd = p.get("render", {})
    road = p.get("road", {})
    zones = p.get("zones", {})

    sun_elev = rd.get("sun_elevation", 40.0)
    sun_rot = rd.get("sun_rotation", 210.0)
    samples = rd.get("samples", 256)

    out_dir = p.get(
        "output_dir", f"{_wb_WORLDBRIDGE_ROOT}/infinigen/outputs/urban_pipeline"
    )

    # Zone dicts
    nw = zones.get("NW", {})
    ne = zones.get("NE", {})
    se = zones.get("SE", {})

    nw_compound = nw.get(
        "compound", {"E": -(G1 + 1.5), "W": -55.0, "S": G1 + 1.5, "N": 58.0}
    )
    nw_apt = nw.get(
        "apartment", {"CX": -33.5, "CY": 34.0, "W": 30.0, "D": 14.0, "floors": 6}
    )
    nw_shrubs = nw.get("shrubs", [])

    ne_trees = ne.get("trees", [])
    ne_pavilion = ne.get("pavilion")
    ne_bandstand = ne.get("bandstand")
    ne_fountain = ne.get("fountain")
    ne_flower_beds = ne.get("flower_beds", [])
    ne_benches = ne.get("benches", [])
    ne_bins = ne.get("bins", [])

    se_shops = se.get("shops", [])
    se_bikestat = se.get("bicycle_station")
    se_kiosk = se.get("kiosk")
    se_phonebooth = se.get("phone_booth")
    se_delivery = se.get("delivery_hub")
    se_benches = se.get("benches", [])
    se_bins = se.get("bins", [])

    # Serialize embedded data as Python literals
    nw_compound_s = repr(nw_compound)
    nw_apt_s = repr(nw_apt)
    nw_shrubs_s = repr(nw_shrubs)
    ne_trees_s = repr(ne_trees)
    ne_pavilion_s = repr(ne_pavilion)
    ne_bandstand_s = repr(ne_bandstand)
    ne_fountain_s = repr(ne_fountain)
    ne_fb_s = repr(ne_flower_beds)
    ne_benches_s = repr(ne_benches)
    ne_bins_s = repr(ne_bins)
    se_shops_s = repr(se_shops)
    se_bikestat_s = repr(se_bikestat)
    se_kiosk_s = repr(se_kiosk)
    se_pb_s = repr(se_phonebooth)
    se_delivery_s = repr(se_delivery)
    se_benches_s = repr(se_benches)
    se_bins_s = repr(se_bins)

    road_tl = "True" if road.get("has_traffic_lights", True) else "False"
    road_xwk = "True" if road.get("has_crosswalks", True) else "False"
    road_mk = "True" if road.get("has_lane_markings", True) else "False"
    road_bs = "True" if road.get("has_bus_stop", True) else "False"
    road_sl = "True" if road.get("has_street_lamps", True) else "False"
    road_fb = "True" if road.get("has_roadside_flower_beds", True) else "False"

    script = f'''\
"""
Generated by WorldBridge Urban Scene Realizer — crossroads_4zone
Run with: blender --background --python <this_file>
"""
from __future__ import annotations
import sys, math, json, os, time
from pathlib import Path
from functools import partial
import builtins
print = partial(builtins.print, flush=True)

REPO  = Path("{_wb_WORLDBRIDGE_ROOT}/infinigen")
CONDA = Path("{_wb_WORLDBRIDGE_SITE_PACKAGES}")
sys.path.insert(0, str(REPO))
if CONDA.exists():
    sys.path.insert(0, str(CONDA))
sys.path.insert(0, "{_wb_WORLDBRIDGE_ROOT}/scripts")

import bpy
import numpy as np
from mathutils import Vector
import gin
import infinigen
from infinigen.core import init as _inf_init
from infinigen.core.util.math import FixedSeed

gin.clear_config()
_inf_init.apply_gin_configs(
    config_folders=[str(REPO / "infinigen_examples/configs_nature")],
    configs=[], overrides=[], skip_unknown=True,
    finalize_config=False, mandatory_folders=[],
)

import urban_assets as UA

PIPELINE_STARTED = time.perf_counter()

OUT      = Path("{out_dir}")
SC_BLEND = Path("{_wb_WORLDBRIDGE_ROOT}/infinigen/outputs/urban_v3_sculpture/public_art.blend")
OX_BASE  = Path("{_wb_WORLDBRIDGE_EXTERNAL}/openx-assets/src/vehicles/main")
OUT.mkdir(parents=True, exist_ok=True)
print("[urban_pipeline] Output:", OUT)

# ─── GPU ─────────────────────────────────────────────────────────────────────
UA.reset_scene()
bpy.context.scene.render.engine = "CYCLES"
for _dt in ("CUDA", "OPTIX", "HIP", "METAL"):
    try:
        _prefs = bpy.context.preferences.addons["cycles"].preferences
        _prefs.compute_device_type = _dt
        _prefs.get_devices()
        for _d in _prefs.devices: _d.use = True
        bpy.context.scene.cycles.device = "GPU"
        print(f"[urban_pipeline] GPU: {{_dt}}"); break
    except Exception as _e:
        print(f"[urban_pipeline] {{_dt}}: {{_e}}")

# ─── EMBEDDED PARAMETERS ─────────────────────────────────────────────────────
R   = {R}
SW  = {SW}
FW  = {FW}
ARM = {ARM}
S1  = {S1}
G1  = {G1}
LC  = {LC}

NW_COMPOUND   = {nw_compound_s}
NW_APT        = {nw_apt_s}
NW_SHRUBS     = {nw_shrubs_s}
NE_TREES      = {ne_trees_s}
NE_PAVILION   = {ne_pavilion_s}
NE_BANDSTAND  = {ne_bandstand_s}
NE_FOUNTAIN   = {ne_fountain_s}
NE_FLOWER_BEDS= {ne_fb_s}
NE_BENCHES    = {ne_benches_s}
NE_BINS       = {ne_bins_s}
SE_SHOPS      = {se_shops_s}
SE_BIKESTAT   = {se_bikestat_s}
SE_KIOSK      = {se_kiosk_s}
SE_PHONEBOOTH = {se_pb_s}
SE_DELIVERY   = {se_delivery_s}
SE_BENCHES    = {se_benches_s}
SE_BINS       = {se_bins_s}

HAS_TRAFFIC_LIGHTS       = {road_tl}
HAS_CROSSWALKS           = {road_xwk}
HAS_LANE_MARKINGS        = {road_mk}
HAS_BUS_STOP             = {road_bs}
HAS_STREET_LAMPS         = {road_sl}
HAS_ROADSIDE_FLOWER_BEDS = {road_fb}

SUN_ELEVATION_DEG = {sun_elev}
SUN_ROTATION_DEG  = {sun_rot}
RENDER_SAMPLES    = {samples}

# ─── MATERIALS ───────────────────────────────────────────────────────────────
def _set(b, k, v):
    if k in b.inputs: b.inputs[k].default_value = v

def _clear_new(name):
    m = bpy.data.materials.get(name)
    if m: return m
    m = bpy.data.materials.new(name); m.use_nodes = True
    for n in list(m.node_tree.nodes): m.node_tree.nodes.remove(n)
    return m

def _sidewalk_mat():
    m = _clear_new("up_sidewalk")
    nt = m.node_tree; nodes, links = nt.nodes, nt.links
    out  = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    tex  = nodes.new("ShaderNodeTexCoord")
    mp   = nodes.new("ShaderNodeMapping"); mp.inputs["Scale"].default_value=(0.4,0.4,1.0)
    links.new(tex.outputs["Object"], mp.inputs["Vector"])
    n1   = nodes.new("ShaderNodeTexNoise"); n1.inputs["Scale"].default_value=7.0; n1.inputs["Detail"].default_value=6.0
    links.new(mp.outputs["Vector"], n1.inputs["Vector"])
    ramp = nodes.new("ShaderNodeValToRGB")
    ramp.color_ramp.elements[0].color=(0.72,0.71,0.69,1.0)
    ramp.color_ramp.elements[1].color=(0.82,0.81,0.79,1.0)
    links.new(n1.outputs["Fac"], ramp.inputs["Fac"])
    links.new(ramp.outputs["Color"], bsdf.inputs["Base Color"])
    _set(bsdf,"Roughness",0.83)
    bump = nodes.new("ShaderNodeBump"); bump.inputs["Strength"].default_value=0.12
    links.new(n1.outputs["Fac"], bump.inputs["Height"])
    links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])
    links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    return m

def _marble_mat():
    m = _clear_new("up_marble")
    nt = m.node_tree; nodes, links = nt.nodes, nt.links
    out  = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    tex  = nodes.new("ShaderNodeTexCoord")
    mp   = nodes.new("ShaderNodeMapping"); mp.inputs["Scale"].default_value=(0.25,0.25,1.0)
    links.new(tex.outputs["Object"], mp.inputs["Vector"])
    n1 = nodes.new("ShaderNodeTexNoise"); n1.inputs["Scale"].default_value=1.8; n1.inputs["Detail"].default_value=12.0; n1.inputs["Distortion"].default_value=1.2
    n2 = nodes.new("ShaderNodeTexNoise"); n2.inputs["Scale"].default_value=5.5; n2.inputs["Detail"].default_value=8.0
    links.new(mp.outputs["Vector"],n1.inputs["Vector"]); links.new(mp.outputs["Vector"],n2.inputs["Vector"])
    r1 = nodes.new("ShaderNodeValToRGB"); r1.color_ramp.elements[0].color=(0.86,0.84,0.80,1.0); r1.color_ramp.elements[1].color=(0.94,0.92,0.90,1.0)
    r2 = nodes.new("ShaderNodeValToRGB"); r2.color_ramp.elements[0].color=(0.58,0.56,0.53,1.0); r2.color_ramp.elements[0].position=0.0; r2.color_ramp.elements[1].color=(0.92,0.90,0.88,1.0); r2.color_ramp.elements[1].position=0.28
    links.new(n1.outputs["Fac"],r1.inputs["Fac"]); links.new(n2.outputs["Fac"],r2.inputs["Fac"])
    mix = nodes.new("ShaderNodeMixRGB"); mix.blend_type="MULTIPLY"; mix.inputs["Fac"].default_value=0.18
    links.new(r1.outputs["Color"],mix.inputs["Color1"]); links.new(r2.outputs["Color"],mix.inputs["Color2"])
    links.new(mix.outputs["Color"],bsdf.inputs["Base Color"]); _set(bsdf,"Roughness",0.06)
    links.new(bsdf.outputs["BSDF"],out.inputs["Surface"])
    return m

def _grass_mat(name="up_grass"):
    m = _clear_new(name)
    nt = m.node_tree; nodes, links = nt.nodes, nt.links
    out  = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    tex  = nodes.new("ShaderNodeTexCoord")
    n1   = nodes.new("ShaderNodeTexNoise"); n1.inputs["Scale"].default_value=12.0; n1.inputs["Detail"].default_value=10.0
    links.new(tex.outputs["Object"],n1.inputs["Vector"])
    ramp = nodes.new("ShaderNodeValToRGB")
    ramp.color_ramp.elements[0].color=(0.035,0.076,0.020,1.0)
    ramp.color_ramp.elements[1].color=(0.075,0.14,0.048,1.0)
    links.new(n1.outputs["Fac"],ramp.inputs["Fac"])
    links.new(ramp.outputs["Color"],bsdf.inputs["Base Color"]); _set(bsdf,"Roughness",0.95)
    links.new(bsdf.outputs["BSDF"],out.inputs["Surface"])
    return m

def _soil_mat():
    m = _clear_new("up_soil")
    nt = m.node_tree; nodes, links = nt.nodes, nt.links
    out  = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    tex  = nodes.new("ShaderNodeTexCoord")
    n1   = nodes.new("ShaderNodeTexNoise"); n1.inputs["Scale"].default_value=8.0; n1.inputs["Detail"].default_value=8.0
    links.new(tex.outputs["Object"],n1.inputs["Vector"])
    ramp = nodes.new("ShaderNodeValToRGB")
    ramp.color_ramp.elements[0].color=(0.21,0.13,0.07,1.0)
    ramp.color_ramp.elements[1].color=(0.30,0.20,0.12,1.0)
    links.new(n1.outputs["Fac"],ramp.inputs["Fac"])
    links.new(ramp.outputs["Color"],bsdf.inputs["Base Color"]); _set(bsdf,"Roughness",0.92)
    links.new(bsdf.outputs["BSDF"],out.inputs["Surface"])
    return m

UA.build_all_materials()
M = UA.M
M["sidewalk"]   = _sidewalk_mat()
M["marble"]     = _marble_mat()
M["grass"]      = _grass_mat("up_grass")
M["soil"]       = _soil_mat()
M["greenstrip"] = _grass_mat("up_gs")
M["grass_park"] = _grass_mat("up_gp")
M["wall_apt"]   = UA._noise_mat("wall_apt",(0.80,0.78,0.74),(0.88,0.86,0.82),rough=0.65,scale=8)
M["balc"]       = UA._pbr("balc",  (0.72,0.70,0.68),rough=0.72)
M["balc_rail"]  = UA._pbr("brail", (0.80,0.82,0.85),rough=0.28,metal=0.88)
M["apt_glass"]  = UA._glass("apt_glass",tint=(0.82,0.90,0.96))
M["apt_roof"]   = UA._pbr("apt_roof",(0.36,0.34,0.33),rough=0.78)
M["shop_w"]     = UA._noise_mat("shop_w",(0.86,0.80,0.68),(0.76,0.70,0.58),rough=0.68,scale=7)
M["shop_r"]     = UA._noise_mat("shop_r",(0.70,0.24,0.14),(0.60,0.18,0.10),rough=0.66,scale=7)
M["shop_b"]     = UA._noise_mat("shop_b",(0.30,0.44,0.72),(0.22,0.36,0.62),rough=0.66,scale=7)
M["awning_r"]   = UA._pbr("awning_r",(0.72,0.18,0.10),rough=0.76)
M["awning_g"]   = UA._pbr("awning_g",(0.18,0.50,0.20),rough=0.76)
M["awning_b"]   = UA._pbr("awning_b",(0.16,0.28,0.70),rough=0.76)
M["fence_iron"] = UA._pbr("fence_iron",(0.08,0.08,0.10),rough=0.32,metal=0.88)
M["gate_post"]  = UA._pbr("gate_post",(0.12,0.12,0.14),rough=0.28,metal=0.92)
M["stone_path"] = UA._noise_mat("stone_path",(0.66,0.62,0.54),(0.56,0.52,0.44),rough=0.76,scale=10)
M["park_stone"] = UA._noise_mat("park_stone",(0.68,0.66,0.60),(0.58,0.56,0.50),rough=0.68,scale=9)
M["water_blue"] = UA._pbr("water_blue",(0.08,0.32,0.72),rough=0.03)
M["pool_rim"]   = UA._pbr("pool_rim",(0.70,0.68,0.64),rough=0.55)
M["sign_comm"]  = UA._pbr("sign_comm",(0.65,0.08,0.08),rough=0.72)
M["route_blue"] = UA._pbr("route_blue",(0.05,0.28,0.78),rough=0.62)
M["tactile"]    = UA._pbr("tactile",(0.92,0.68,0.06),rough=0.74)
_SHOP_MATS = {{"w": M["shop_w"], "r": M["shop_r"], "b": M["shop_b"]}}
_AWN_MATS  = {{"r": M["awning_r"], "g": M["awning_g"], "b": M["awning_b"]}}

# ─── PROC SHRUB FACTORY (all8-quality) ──────────────────────────────────────
def _nrm(v):
    vec=Vector(v); l=vec.length; return vec/l if l>1e-8 else Vector((0,0,1))
def _pfrm(d):
    d=_nrm(d); ref=Vector((0,0,1)) if abs(d.z)<0.85 else Vector((1,0,0))
    r=d.cross(ref).normalized(); u=d.cross(r).normalized(); return r,u
def _lerp3(a,b,t): return (a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t)
def _bez3(p0,p1,p2,t): q0=_lerp3(p0,p1,t); q1=_lerp3(p1,p2,t); return _lerp3(q0,q1,t)
def _tapcyl(verts,faces,pts,radii,ns=6):
    rs=[]
    for i,(pt,r) in enumerate(zip(pts,radii)):
        d=_nrm(Vector(pts[1])-Vector(pts[0])) if i==0 else _nrm(Vector(pts[i])-Vector(pts[i-1]))
        right,up=_pfrm(d); rs.append(len(verts))
        for j in range(ns):
            a=j/ns*math.tau; v=Vector(pt)+right*(r*math.cos(a))+up*(r*math.sin(a)); verts.append(tuple(v))
    for i in range(len(rs)-1):
        s0,s1=rs[i],rs[i+1]
        for j in range(ns): jn=(j+1)%ns; faces.append((s0+j,s0+jn,s1+jn,s1+j))
def _addleaf(verts,faces,c,t,b,ln,wd):
    c=Vector(c); t=_nrm(t); b=_nrm(b)
    tip=c+t*ln*0.60; rsh=c+t*ln*0.08+b*wd*0.50; rba=c-t*ln*0.32+b*wd*0.18
    base=c-t*ln*0.40; lba=c-t*ln*0.32-b*wd*0.18; lsh=c+t*ln*0.08-b*wd*0.50
    i=len(verts); verts+=[tuple(tip),tuple(rsh),tuple(rba),tuple(base),tuple(lba),tuple(lsh)]
    faces+=[(i,i+1,i+5),(i+1,i+2,i+5),(i+2,i+4,i+5),(i+2,i+3,i+4)]
def _leafcluster(verts,faces,tip,rng,n,lsz,sp):
    tip=Vector(tip)
    for _ in range(n):
        off=Vector((rng.uniform(-sp,sp),rng.uniform(-sp,sp),rng.uniform(-sp*0.4,sp*0.4)))
        center=tip+off; ow=(off+Vector((0,0,0.01))).normalized()
        uv=Vector((rng.uniform(-.3,.3),rng.uniform(-.3,.3),1.0)).normalized()
        tg=(ow*0.6+uv*0.4).normalized()
        bt=tg.cross(Vector((rng.uniform(-1,1),rng.uniform(-1,1),rng.uniform(-.2,.2))).normalized()).normalized()
        _addleaf(verts,faces,center,tg,bt,lsz*rng.uniform(0.8,1.3),lsz*rng.uniform(0.32,0.52))
def _shrub_bark(seed):
    mat=bpy.data.materials.new(f"UPBark{{seed}}"); mat.use_nodes=True; nt=mat.node_tree; nt.nodes.clear()
    out=nt.nodes.new("ShaderNodeOutputMaterial"); bsdf=nt.nodes.new("ShaderNodeBsdfPrincipled")
    noise=nt.nodes.new("ShaderNodeTexNoise"); ramp=nt.nodes.new("ShaderNodeValToRGB"); coord=nt.nodes.new("ShaderNodeTexCoord")
    noise.inputs["Scale"].default_value=14.0; noise.inputs["Detail"].default_value=6.0
    ramp.color_ramp.elements[0].color=(0.030,0.016,0.006,1.0); ramp.color_ramp.elements[1].color=(0.078,0.042,0.015,1.0); bsdf.inputs["Roughness"].default_value=0.92
    nt.links.new(coord.outputs["Generated"],noise.inputs["Vector"]); nt.links.new(noise.outputs["Fac"],ramp.inputs["Fac"]); nt.links.new(ramp.outputs["Color"],bsdf.inputs["Base Color"]); nt.links.new(bsdf.outputs["BSDF"],out.inputs["Surface"])
    return mat
def _shrub_leaf(seed):
    rng=np.random.default_rng(seed); mat=bpy.data.materials.new(f"UPLeaf{{seed}}"); mat.use_nodes=True; mat.use_backface_culling=False
    nt=mat.node_tree; nt.nodes.clear()
    out=nt.nodes.new("ShaderNodeOutputMaterial"); mxs=nt.nodes.new("ShaderNodeMixShader"); bsdf=nt.nodes.new("ShaderNodeBsdfPrincipled"); trans=nt.nodes.new("ShaderNodeBsdfTranslucent")
    noise=nt.nodes.new("ShaderNodeTexNoise"); ramp=nt.nodes.new("ShaderNodeValToRGB"); coord=nt.nodes.new("ShaderNodeTexCoord")
    noise.inputs["Scale"].default_value=float(rng.uniform(6,12)); noise.inputs["Detail"].default_value=5.0
    h=rng.uniform(-0.03,0.03)
    ramp.color_ramp.elements[0].color=(max(0,0.013+h),0.068,max(0,0.009+h),1.0); ramp.color_ramp.elements[1].color=(max(0,0.038+h),0.148,max(0,0.020+h),1.0); ramp.color_ramp.elements[1].position=0.7
    bsdf.inputs["Roughness"].default_value=float(rng.uniform(0.58,0.72)); mxs.inputs["Fac"].default_value=0.25
    nt.links.new(coord.outputs["Generated"],noise.inputs["Vector"]); nt.links.new(noise.outputs["Fac"],ramp.inputs["Fac"]); nt.links.new(ramp.outputs["Color"],bsdf.inputs["Base Color"]); nt.links.new(ramp.outputs["Color"],trans.inputs["Color"]); nt.links.new(bsdf.outputs["BSDF"],mxs.inputs[2]); nt.links.new(trans.outputs["BSDF"],mxs.inputs[1]); nt.links.new(mxs.outputs["Shader"],out.inputs["Surface"])
    return mat
class ProcShrubFactory:
    def __init__(self,seed=0,max_spread=0.22,max_height=1.1):
        self.seed=seed; rng=np.random.default_rng(seed)
        self.n_stems=int(rng.integers(4,8)); self.max_height=float(rng.uniform(0.70,max_height)); self.base_spread=float(rng.uniform(0.12,max_spread)); self.leaf_size=float(rng.uniform(0.050,0.078)); self._rng=rng
    def _stem_path(self,base,angle,lean,height):
        rng=self._rng; tip=(base[0]+lean*math.cos(angle),base[1]+lean*math.sin(angle),base[2]+height)
        ctrl=_lerp3(base,tip,0.5); ctrl=(ctrl[0]+rng.uniform(-.05,.05),ctrl[1]+rng.uniform(-.05,.05),ctrl[2]+rng.uniform(-.03,.06))
        return [_bez3(base,ctrl,tip,t) for t in np.linspace(0,1,4)]
    def create_asset(self,location=(0.,0.,0.),name="Shrub",coll=None):
        rng=self._rng; bm=_shrub_bark(self.seed); lm=_shrub_leaf(self.seed)
        sv,sf=[],[]; lv,lf=[],[]; tips=[]
        for i in range(self.n_stems):
            ang=i/self.n_stems*math.tau+rng.uniform(-.25,.25); lean=self.base_spread*rng.uniform(0.5,1.0); h=self.max_height*rng.uniform(0.70,1.20)
            base=(location[0]+math.cos(ang)*0.03,location[1]+math.sin(ang)*0.03,location[2])
            path=self._stem_path(base,ang,lean,h); radii=np.linspace(0.018,0.004,4).tolist(); _tapcyl(sv,sf,path,radii,6)
            for _ in range(int(rng.integers(2,4))):
                t=rng.uniform(.45,.80); pt=_bez3(path[0],path[1],path[-1],t)
                ba=rng.uniform(0,math.tau); be=rng.uniform(math.radians(25),math.radians(68)); bl=h*rng.uniform(.20,.40)
                btp=(pt[0]+bl*math.cos(ba)*math.cos(be),pt[1]+bl*math.sin(ba)*math.cos(be),pt[2]+bl*math.sin(be))
                bc=_lerp3(pt,btp,.5); bp=[_bez3(pt,bc,btp,t2) for t2 in np.linspace(0,1,3)]
                _tapcyl(sv,sf,bp,[0.009,0.006,0.003],5); tips.append(btp)
        n_per_tip=int(rng.integers(12,18))
        for tip in tips: _leafcluster(lv,lf,tip,rng,n_per_tip,self.leaf_size,self.leaf_size*1.1)
        sm=bpy.data.meshes.new(name+"_b"); sm.from_pydata(sv,[],sf); sm.update()
        so=bpy.data.objects.new(name+"_b",sm); bpy.context.collection.objects.link(so); so.data.materials.append(bm)
        lm2=bpy.data.meshes.new(name+"_l"); lm2.from_pydata(lv,[],lf); lm2.update()
        for p in lm2.polygons: p.use_smooth=True
        lo=bpy.data.objects.new(name+"_l",lm2); bpy.context.collection.objects.link(lo); lo.data.materials.append(lm); lo.parent=so
        bpy.context.view_layer.update()
        if coll: UA.to_coll(so,coll); UA.to_coll(lo,coll)
        return so

def _place_shrubs_along(tag,cx,cy,lx,ly,C,spacing=2.2,seed=0):
    rng_sp=np.random.default_rng(seed%99991)
    nx=max(1,int(lx/spacing)); ny=max(1,int(ly/spacing)); k=0
    for i in range(nx):
        for j in range(ny):
            x=cx-lx/2+(i+0.5)*lx/nx+float(rng_sp.uniform(-0.3,0.3))
            y=cy-ly/2+(j+0.5)*ly/ny+float(rng_sp.uniform(-0.3,0.3))
            sh_seed=(seed*1000+k)%99991
            ProcShrubFactory(seed=sh_seed,max_spread=0.20,max_height=0.95).create_asset(location=(x,y,0.08),name=f"{{tag}}_sh{{k}}",coll=C)
            k+=1

# ─── FLOWER-BED BELT HELPERS ─────────────────────────────────────────────────
def _fb_ground(tag,cx,cy,dx,dy,C): UA._box(tag+"_g",cx,cy,0.04,dx,dy,0.08,M["greenstrip"],C)
def _fb_ns(tag,x_inner,side,y0,y1,C):
    if y1<=y0: return
    fw2=FW/2.0; cx=x_inner+(fw2 if side=="e" else -fw2); cy=(y0+y1)/2.0; dy=y1-y0
    UA._box(tag+"_g",cx,cy,0.04,FW,dy,0.08,M["greenstrip"],C)
    if dy>=1.5:
        _place_shrubs_along(tag,cx,cy,FW-0.3,dy-0.3,C,spacing=2.2,seed=abs(hash(tag))%99991)
def _fb_ew(tag,y_inner,side,x0,x1,C):
    if x1<=x0: return
    fw2=FW/2.0; cy=y_inner+(fw2 if side=="n" else -fw2); cx=(x0+x1)/2.0; dx=x1-x0
    UA._box(tag+"_g",cx,cy,0.04,dx,FW,0.08,M["greenstrip"],C)
    if dx>=1.5:
        _place_shrubs_along(tag,cx,cy,dx-0.3,FW-0.3,C,spacing=2.2,seed=abs(hash(tag))%99991)

# ─── TREEFACTORY PARK TREE (infinigen, fallback to procedural) ────────────────
def _gen_park_tree(tag, tx, ty, C, seed=42, scale=1.0):
    print(f"[urban_pipeline] Tree {{tag}} at ({{tx:.1f}},{{ty:.1f}}) seed={{seed}} ...")
    cached = UA.place_infinigen_tree(tag, (tx, ty), C, tree_idx=seed % 5, scale=scale)
    if cached:
        print(f"[urban_pipeline] Tree {{tag}} done (prototype instance)")
        return cached[0]
    try:
        from infinigen.assets.objects.trees.generate import TreeFactory
        with FixedSeed(seed):
            fac = TreeFactory(seed=seed, season="summer", coarse=False, fruit_chance=0.0)
            root = fac.spawn_asset(0, loc=(tx, ty, 0), rot=(0, 0, 0))
        if root:
            if scale != 1.0:
                root.scale = (scale, scale, scale)
            UA.to_coll(root, C)
            for o in list(bpy.data.objects):
                if o != root and o.parent is root:
                    UA.to_coll(o, C)
            print(f"[urban_pipeline] Tree {{tag}} done (TreeFactory)")
        return root
    except Exception as _e:
        print(f"[urban_pipeline] TreeFactory fallback for {{tag}}: {{_e}}")
        rng=np.random.default_rng(seed)
        trunk_h=float(rng.uniform(4.6,6.1)*scale); trunk_r=float(rng.uniform(0.18,0.28)*scale)
        UA._cyl(f"{{tag}}_trunk",tx,ty,0.0,trunk_r,trunk_h,M["tree_trunk"],C,verts=14)
        for bi in range(6):
            a=bi/6.0*math.tau+float(rng.uniform(-0.22,0.22)); length=float(rng.uniform(1.4,2.4)*scale)
            z=trunk_h*float(rng.uniform(0.55,0.88)); bx_=tx+math.cos(a)*length*0.30; by_=ty+math.sin(a)*length*0.30
            br=UA._cyl(f"{{tag}}_br{{bi}}",bx_,by_,z,trunk_r*0.32,length,M["tree_trunk"],C,verts=8,rx=math.radians(62),rz=a)
            br.scale.x*=float(rng.uniform(0.75,1.10))
        for ci,(ox,oy,oz,rr) in enumerate([(0,0,1.05,2.5),(0.9,0.3,0.55,1.65),(-0.9,-0.2,0.50,1.65),(0.0,1.0,0.45,1.55),(0.1,-1.0,0.35,1.45),(0.0,0.0,1.75,1.55)]):
            jx=float(rng.uniform(-0.22,0.22)); jy=float(rng.uniform(-0.22,0.22))
            UA._sph(f"{{tag}}_can{{ci}}",tx+(ox+jx)*scale,ty+(oy+jy)*scale,trunk_h+oz*scale,rr*scale*float(rng.uniform(0.88,1.12)),M["tree_leaf"],C,segs=18,rings=12)
        print(f"[urban_pipeline] Tree {{tag}} done (fallback)")
        return None

# ─── COLLECTIONS ─────────────────────────────────────────────────────────────
C_road = UA.new_coll("Road");    C_sw   = UA.new_coll("Sidewalks"); C_fb = UA.new_coll("FlowerBeds")
C_mk   = UA.new_coll("RoadMarkings"); C_tl = UA.new_coll("TrafficLights")
C_res  = UA.new_coll("Residential"); C_park = UA.new_coll("Park")
C_com  = UA.new_coll("Commercial"); C_empty = UA.new_coll("Empty")
C_furn = UA.new_coll("Furniture"); C_lamp = UA.new_coll("Lamps")
C_cars = UA.new_coll("Vehicles"); C_tree = UA.new_coll("Trees")

def _box(n,cx,cy,cz,dx,dy,dz,mat,coll,bev=0.0,rz=0.0): return UA._box(n,cx,cy,cz,dx,dy,dz,mat,coll,bev=bev,rz=rz)
def _cyl(n,cx,cy,cz,r,h,mat,coll,verts=24,rx=0.0,rz=0.0): return UA._cyl(n,cx,cy,cz,r,h,mat,coll,verts=verts,rx=rx,rz=rz)
def _sph(n,cx,cy,cz,r,mat,coll,segs=16,rings=12): return UA._sph(n,cx,cy,cz,r,mat,coll,segs=segs,rings=rings)

# ─── GROUND ──────────────────────────────────────────────────────────────────
_box("gnd",0,0,-0.10,400,400,0.20,M["soil"],C_sw)
bpy.ops.mesh.primitive_grid_add(x_subdivisions=250,y_subdivisions=250,size=1.0,location=(G1+ARM/2,G1+ARM/2,0.005))
park_gnd=bpy.context.active_object; park_gnd.name="park_lawn_grid"
park_gnd.scale=(ARM,ARM,1.0); bpy.ops.object.transform_apply(scale=True)
park_gnd.data.materials.append(M["grass_park"]); UA.to_coll(park_gnd,C_park)
_box("sw_lawn",-(G1+ARM/2),-(G1+ARM/2),0.005,ARM,ARM,0.01,M["grass"],C_empty)

# ─── ROAD + SIDEWALK + KERBS ─────────────────────────────────────────────────
_box("isect",0,0,-0.02,2*R,2*R,0.04,M["road"],C_road)
for ys,t in [(+1,"n"),(-1,"s")]:
    yc=ys*(R+ARM/2)
    _box(f"road_{{t}}",0,yc,-0.02,2*R,ARM,0.04,M["road"],C_road)
    _box(f"sw_{{t}}_e", S1-SW/2,yc,0.06,SW,ARM,0.12,M["sidewalk"],C_sw)
    _box(f"sw_{{t}}_w",-(S1-SW/2),yc,0.06,SW,ARM,0.12,M["sidewalk"],C_sw)
    _box(f"kb_{{t}}_e", R+0.08,yc,0.10,0.16,ARM,0.20,M["curb"],C_sw)
    _box(f"kb_{{t}}_w",-R-0.08,yc,0.10,0.16,ARM,0.20,M["curb"],C_sw)
for xs,t in [(+1,"e"),(-1,"w")]:
    xc=xs*(R+ARM/2)
    _box(f"road_{{t}}",xc,0,-0.02,ARM,2*R,0.04,M["road"],C_road)
    _box(f"sw_{{t}}_n",xc, S1-SW/2,0.06,ARM,SW,0.12,M["sidewalk"],C_sw)
    _box(f"sw_{{t}}_s",xc,-(S1-SW/2),0.06,ARM,SW,0.12,M["sidewalk"],C_sw)
    _box(f"kb_{{t}}_n",xc, R+0.08,0.10,ARM,0.16,0.20,M["curb"],C_sw)
    _box(f"kb_{{t}}_s",xc,-R-0.08,0.10,ARM,0.16,0.20,M["curb"],C_sw)
for xs,ys in [(1,1),(1,-1),(-1,1),(-1,-1)]:
    _box(f"sw_cor{{xs}}{{ys}}",xs*(R+SW/2),ys*(R+SW/2),0.06,SW,SW,0.12,M["sidewalk"],C_sw)

# ─── ROAD MARKINGS ───────────────────────────────────────────────────────────
if HAS_LANE_MARKINGS:
    for dx in (-0.08,0.08):
        _box(f"cl_ns_{{dx:.2f}}",dx,0,0.003,0.06,2*(R+ARM),0.004,M["stripe_y"],C_mk)
        _box(f"cl_ew_{{dx:.2f}}",0,dx,0.003,2*(R+ARM),0.06,0.004,M["stripe_y"],C_mk)
    for yi in range(2,10):
        y0=R+yi*(ARM/10)
        for side in [LC,-LC]:
            _box(f"dash_n{{yi}}_{{side:.2f}}",side, y0,0.003,0.12,1.8,0.004,M["stripe_w"],C_mk)
            _box(f"dash_s{{yi}}_{{side:.2f}}",side,-y0,0.003,0.12,1.8,0.004,M["stripe_w"],C_mk)
    for xi in range(2,10):
        x0=R+xi*(ARM/10)
        for side in [LC,-LC]:
            _box(f"dash_e{{xi}}_{{side:.2f}}", x0,side,0.003,1.8,0.12,0.004,M["stripe_w"],C_mk)
            _box(f"dash_w{{xi}}_{{side:.2f}}",-x0,side,0.003,1.8,0.12,0.004,M["stripe_w"],C_mk)
if HAS_CROSSWALKS:
    for stripe in range(8):
        xf=-R+0.5+stripe*(2*R-1.0)/8
        _box(f"xwk_s{{stripe}}",xf,-(R+0.6),0.004,0.78,2.2,0.005,M["xwalk"],C_mk)
        _box(f"xwk_n{{stripe}}",xf, (R+0.6),0.004,0.78,2.2,0.005,M["xwalk"],C_mk)
    for stripe in range(8):
        yf=-R+0.5+stripe*(2*R-1.0)/8
        _box(f"xwk_e{{stripe}}", (R+0.6),yf,0.004,2.2,0.78,0.005,M["xwalk"],C_mk)
        _box(f"xwk_w{{stripe}}",-(R+0.6),yf,0.004,2.2,0.78,0.005,M["xwalk"],C_mk)
    for sign,sfx in [(1,"n"),(-1,"s")]:
        _box(f"stop_{{sfx}}",0,sign*(R+2.0),0.004,2*R,0.4,0.005,M["stripe_w"],C_mk)
    for sign,sfx in [(1,"e"),(-1,"w")]:
        _box(f"stop_{{sfx}}",sign*(R+2.0),0,0.004,0.4,2*R,0.005,M["stripe_w"],C_mk)

# ─── TRAFFIC LIGHTS ──────────────────────────────────────────────────────────
if HAS_TRAFFIC_LIGHTS:
    UA.place_trafficlight((0.0,-(R+2.6)),C_tl,yaw=0)
    UA.place_trafficlight((0.0, (R+2.6)),C_tl,yaw=math.pi)
    UA.place_trafficlight((-(R+2.6),0.0),C_tl,yaw=-math.pi/2)
    UA.place_trafficlight(( (R+2.6),0.0),C_tl,yaw= math.pi/2)

# ─── ROADSIDE FLOWER BEDS ────────────────────────────────────────────────────
if HAS_ROADSIDE_FLOWER_BEDS:
    print("[urban_pipeline] Building roadside flower beds ...")
    _fb_ns("fb_ne1", S1,"e", R,    11.0,  C_fb)
    _fb_ns("fb_ne2", S1,"e", 15.5, R+ARM, C_fb)
    _fb_ns("fb_nw1",-S1,"w", R,    R+ARM, C_fb)
    _fb_ns("fb_se1", S1,"e",-(R+ARM),-R,  C_fb)
    _fb_ns("fb_sw1",-S1,"w",-(R+ARM),-R,  C_fb)
    _fb_ew("fb_en1", S1,"n", R,    12.0,  C_fb)
    _fb_ew("fb_en2", S1,"n", 17.0, R+ARM, C_fb)
    _fb_ew("fb_es1",-S1,"s", R,    R+ARM, C_fb)
    _fb_ew("fb_wn1", S1,"n",-(R+ARM),-R,  C_fb)
    _fb_ew("fb_ws1",-S1,"s",-(R+ARM),-R,  C_fb)
    print("[urban_pipeline] Flower beds done.")

# ─── STREET LAMPS ────────────────────────────────────────────────────────────
if HAS_STREET_LAMPS:
    for y in [8,16,24,32,40,48]:
        UA.place_streetlight(( S1-SW/2,y),C_lamp,yaw= math.pi/2,day=True)
        UA.place_streetlight((-S1+SW/2,y),C_lamp,yaw=-math.pi/2,day=True)
    for y in [-8,-16,-24,-32,-40,-48]:
        UA.place_streetlight(( S1-SW/2,y),C_lamp,yaw= math.pi/2,day=True)
        UA.place_streetlight((-S1+SW/2,y),C_lamp,yaw=-math.pi/2,day=True)
    for x in [8,16,24,32,40,48]:
        UA.place_streetlight((x, S1-SW/2),C_lamp,yaw=math.pi,day=True)
        UA.place_streetlight((x,-S1+SW/2),C_lamp,yaw=0.0,    day=True)
    for x in [-8,-16,-24,-32,-40,-48]:
        UA.place_streetlight((x, S1-SW/2),C_lamp,yaw=math.pi,day=True)
        UA.place_streetlight((x,-S1+SW/2),C_lamp,yaw=0.0,    day=True)

# ─── BUS STOP ────────────────────────────────────────────────────────────────
if HAS_BUS_STOP:
    UA.place_busstop((S1-SW/2,13.0),C_furn,yaw=-math.pi/2,scale=1.4)

# ═══════════════════════════════════════════════════════════════════════════════
# NW — RESIDENTIAL
# ═══════════════════════════════════════════════════════════════════════════════
print("[urban_pipeline] Building residential zone ...")
CMP_E=NW_COMPOUND["E"]; CMP_W=NW_COMPOUND["W"]
CMP_S=NW_COMPOUND["S"]; CMP_N=NW_COMPOUND["N"]
CMP_CX=(CMP_E+CMP_W)/2; CMP_CY=(CMP_S+CMP_N)/2
_box("res_marble",CMP_CX,CMP_CY,0.01,abs(CMP_W-CMP_E),CMP_N-CMP_S,0.02,M["marble"],C_res)
FH=1.6; GATE_W=4.5; GHW=GATE_W/2; CW=abs(CMP_W-CMP_E); CD=CMP_N-CMP_S
_box("res_fn",CMP_CX,CMP_N,FH/2,CW,0.10,FH,M["fence_iron"],C_res)
_box("res_fe",CMP_E,CMP_CY,FH/2,0.10,CD,FH,M["fence_iron"],C_res)
_box("res_fw",CMP_W,CMP_CY,FH/2,0.10,CD,FH,M["fence_iron"],C_res)
for x0,x1,sfx in [(CMP_E,CMP_CX-GHW,"lo"),(CMP_CX+GHW,CMP_W,"hi")]:
    seg=abs(x1-x0)
    if seg>0.2: _box(f"res_fs_{{sfx}}",(x0+x1)/2,CMP_S,FH/2,seg,0.10,FH,M["fence_iron"],C_res)
for gx in [CMP_CX-GHW,CMP_CX+GHW]: _cyl(f"res_gp{{gx:.0f}}",gx,CMP_S,0,0.12,FH+0.5,M["gate_post"],C_res,verts=8)
for px,py in [(CMP_E,CMP_N),(CMP_W,CMP_N),(CMP_E,CMP_S),(CMP_W,CMP_S)]:
    _cyl(f"res_cp{{px:.0f}}{{py:.0f}}",px,py,0,0.10,FH+0.3,M["gate_post"],C_res,verts=8)
APT_CX=NW_APT["CX"]; APT_CY=NW_APT["CY"]; APT_SY=APT_CY-NW_APT["D"]/2
_box("res_ep",CMP_CX,(CMP_S+APT_SY)/2,0.03,GATE_W+0.5,APT_SY-CMP_S,0.04,M["stone_path"],C_res)
APT_W=NW_APT["W"]; APT_D=NW_APT["D"]; APT_FL=NW_APT["floors"]; APT_FH=3.2
APT_H=APT_FL*APT_FH
_box("apt_body",APT_CX,APT_CY,APT_H/2,APT_W,APT_D,APT_H,M["wall_apt"],C_res,bev=0.02)
_box("apt_roof",APT_CX,APT_CY,APT_H+0.10,APT_W,APT_D,0.20,M["apt_roof"],C_res)
_box("apt_prpt",APT_CX,APT_SY,APT_H+0.42,APT_W+0.10,0.40,0.85,M["balc"],C_res)
N_COLS=8
for fl in range(APT_FL):
    z_w=fl*APT_FH+APT_FH*0.52
    for col in range(N_COLS):
        wx=APT_CX-APT_W/2+(col+0.5)*APT_W/N_COLS
        if fl==0 and abs(col-3.5)<1.1: continue
        _box(f"apt_w{{fl}}_{{col}}",wx,APT_SY-0.06,z_w,APT_W/N_COLS*0.58,0.12,APT_FH*0.58,M["apt_glass"],C_res)
_box("apt_lobby",APT_CX,APT_SY-0.06,APT_FH*0.62,5.8,0.14,APT_FH*1.24,M["apt_glass"],C_res)
_box("apt_canopy",APT_CX,APT_SY-1.8,APT_H*0.20,8.0,3.6,0.18,M["apt_roof"],C_res)
N_BALC=6
for fl in range(1,APT_FL):
    z_f=fl*APT_FH
    for b in range(N_BALC):
        bx_=APT_CX-APT_W/2+(b+0.5)*APT_W/N_BALC
        _box(f"apt_bs{{fl}}_{{b}}",bx_,APT_SY-1.0,z_f+0.10,APT_W/N_BALC*0.78,2.0,0.14,M["balc"],C_res)
        _box(f"apt_br{{fl}}_{{b}}",bx_,APT_SY-1.95,z_f+0.72,APT_W/N_BALC*0.78,0.06,1.10,M["balc_rail"],C_res)
for i,(sx,sy,sd) in enumerate(NW_SHRUBS):
    ProcShrubFactory(seed=sd,max_spread=0.22,max_height=1.2).create_asset(location=(sx,sy,0.04),name=f"ysh{{i}}",coll=C_res)
print("[urban_pipeline] Residential done.")

# ═══════════════════════════════════════════════════════════════════════════════
# NE — PARK
# ═══════════════════════════════════════════════════════════════════════════════
print("[urban_pipeline] Building park zone ...")
PARK_X0=G1; PARK_X1=G1+ARM; PARK_Y0=G1; PARK_Y1=G1+ARM
PARK_CX=(PARK_X0+PARK_X1)/2; PARK_CY=(PARK_Y0+PARK_Y1)/2

# Lawn flower clusters
_flower_mats=[M["flower_r"],M["flower_y"],M["flower_p"],M["flower_w"]]
for pi_,(px_,py_,rad,seed0) in enumerate([
    (21,17,2.6,410),(31,17,2.2,420),(43,18,2.4,430),(52,22,2.0,440),
    (22,34,2.4,450),(31,41,2.2,460),(42,44,2.6,470),(52,36,2.0,480)]):
    rngf=np.random.default_rng(seed0)
    for k in range(24):
        rr_=rad*math.sqrt(float(rngf.uniform(0.0,1.0))); aa_=float(rngf.uniform(0.0,math.tau))
        fx_,fy_=px_+rr_*math.cos(aa_),py_+rr_*math.sin(aa_)
        if not(PARK_X0+1.0<=fx_<=PARK_X1-1.0 and PARK_Y0+1.0<=fy_<=PARK_Y1-1.0): continue
        sh=float(rngf.uniform(0.12,0.28))
        _cyl(f"pk_fl_st{{pi_}}_{{k}}",fx_,fy_,0.06,0.007,sh,M["flower_leaf"],C_park,verts=5)
        _sph(f"pk_fl_bl{{pi_}}_{{k}}",fx_,fy_,0.06+sh,float(rngf.uniform(0.035,0.060)),
             _flower_mats[int(rngf.integers(0,len(_flower_mats)))],C_park,segs=7,rings=5)

_cyl("pk_gp1",14.0,G1+0.3,0,0.15,2.6,M["gate_post"],C_park,verts=8)
_cyl("pk_gp2",17.0,G1+0.3,0,0.15,2.6,M["gate_post"],C_park,verts=8)
_box("pk_ep",15.5,(S1+G1)/2,0.04,4.5,FW,0.08,M["stone_path"],C_park)
_box("ppth_ns",16.0,PARK_CY,0.05,2.5,PARK_Y1-PARK_Y0,0.10,M["park_stone"],C_park)
_box("ppth_ew",PARK_CX,28.0,0.05,PARK_X1-PARK_X0,2.5,0.10,M["park_stone"],C_park)
_box("ppth_s2",PARK_CX,20.0,0.05,PARK_X1-PARK_X0,2.0,0.10,M["park_stone"],C_park)
bpy.ops.mesh.primitive_cylinder_add(vertices=32,radius=6.2,depth=0.10,location=(34,32,0.06))
plz=bpy.context.active_object; plz.name="pk_plaza"; plz.data.materials.append(M["park_stone"]); UA.to_coll(plz,C_park)

if NE_PAVILION:
    pav_objs=UA._import_prefix(SC_BLEND,"pav:",C_park)
    if pav_objs: UA._place(pav_objs,NE_PAVILION[0],NE_PAVILION[1]); print(f"[urban_pipeline] Pavilion placed")
    else:
        _cyl("pav_base",34,32,0,4.2,0.35,M["park_stone"],C_park,verts=6)
        for i in range(6):
            a=i*math.pi/3; _cyl(f"pav_col{{i}}",34+2.6*math.cos(a),32+2.6*math.sin(a),0.35,0.18,3.4,M["park_stone"],C_park,verts=12)
        bpy.ops.mesh.primitive_cone_add(radius1=3.8,radius2=0.25,depth=1.8,location=(34,32,5.15))
        cn=bpy.context.active_object; cn.name="pav_cone"; cn.data.materials.append(M["roof_tile"]); UA.to_coll(cn,C_park)

if NE_BANDSTAND:
    band_objs=UA._import_prefix(SC_BLEND,"band:",C_park)
    if band_objs: UA._place(band_objs,NE_BANDSTAND[0],NE_BANDSTAND[1]); print("[urban_pipeline] Bandstand placed")

# chrome trefoil sculpture
_mat_ct=UA._pbr("ct_mat",(0.48,0.22,0.06),rough=0.72)
for i in range(3):
    ang=i*math.pi/3; ox,oy=48+math.cos(ang)*1.2,20+math.sin(ang)*1.2
    bpy.ops.mesh.primitive_torus_add(major_radius=1.5,minor_radius=0.18,location=(ox,oy,1.8+0.3),rotation=(math.radians(60+i*30),0,ang))
    o=bpy.context.active_object; o.name=f"ct_ring{{i}}"; o.data.materials.append(_mat_ct); UA.to_coll(o,C_park)

if NE_FOUNTAIN:
    _cyl("fnt_rim", NE_FOUNTAIN[0],NE_FOUNTAIN[1],0.0,2.5,0.44,M["pool_rim"],C_park,verts=32)
    _fountain_pool=_cyl("fnt_pool",NE_FOUNTAIN[0],NE_FOUNTAIN[1],0.08,2.2,0.30,M["water_blue"],C_park,verts=32)
    _fountain_pool["c2w_dynamic_role"]="fountain"
    _cyl("fnt_col", NE_FOUNTAIN[0],NE_FOUNTAIN[1],0.38,0.14,1.40,M["pool_rim"],C_park,verts=12)
    _sph("fnt_top", NE_FOUNTAIN[0],NE_FOUNTAIN[1],2.04+0.26,0.26,M["water_blue"],C_park,segs=12,rings=8)

for pi_,(px_,py_,dx_,dy_) in enumerate(NE_FLOWER_BEDS or []):
    tag_=f"pfb{{pi_}}"
    _fb_ground(tag_,px_,py_,dx_,dy_,C_park)
    rng2=np.random.default_rng(abs(hash(tag_))%99991)
    for k in range(6):
        sx_=px_+float(rng2.uniform(-dx_/2+0.4,dx_/2-0.4)); sy_=py_+float(rng2.uniform(-dy_/2+0.3,dy_/2-0.3))
        ProcShrubFactory(seed=(abs(hash(tag_))+k)%99991,max_spread=0.24,max_height=1.2).create_asset(location=(sx_,sy_,0.05),name=f"pfb{{pi_}}_s{{k}}",coll=C_park)

for bx2_,by2_,byw_ in NE_BENCHES:
    UA.place_bench_classic((bx2_,by2_),C_park,yaw=byw_)
for bx2_,by2_ in NE_BINS:
    UA.place_bin_domed((bx2_,by2_),C_park)

print("[urban_pipeline] Placing park trees ...")
for i,(t) in enumerate(NE_TREES):
    _gen_park_tree(f"pk_tr{{i}}",t["x"],t["y"],C_tree,seed=t["seed"],scale=t["scale"])
print("[urban_pipeline] Park done.")

# ═══════════════════════════════════════════════════════════════════════════════
# SE — COMMERCIAL
# ═══════════════════════════════════════════════════════════════════════════════
print("[urban_pipeline] Building commercial zone ...")
COM_X0,COM_X1=G1,G1+ARM; COM_Y0,COM_Y1=-(G1+ARM),-G1
_box("com_marble",(COM_X0+COM_X1)/2,(COM_Y0+COM_Y1)/2,0.01,ARM,ARM,0.02,M["marble"],C_com)

SHOP_D=14.0; SHOP_H=5.0; SHOP_W=14.0
def _shopW(tag,cx,cy,w,d,h,mat,aw_mat,C):
    _box(f"{{tag}}_b",cx,cy,h/2,d,w,h,mat,C,bev=0.02)
    _box(f"{{tag}}_gl",cx-d/2+0.08,cy,h*0.38,0.10,w*0.68,h*0.52,M["apt_glass"],C)
    _box(f"{{tag}}_aw",cx-d/2-0.80,cy,h*0.72,1.60,w*0.82,0.12,aw_mat,C,rz=math.radians(-5))
    _box(f"{{tag}}_sg",cx-d/2+0.08,cy,h*0.86,0.16,w*0.72,0.50,M["sign_comm"],C)
    _box(f"{{tag}}_dr",cx-d/2+0.06,cy,1.25,0.12,1.20,2.50,M["door"],C)

for idx_,sh in enumerate(SE_SHOPS):
    _shopW(f"sh{{idx_}}",sh["x"],sh["y"],SHOP_W,SHOP_D,SHOP_H,
           _SHOP_MATS.get(sh["mat"],M["shop_w"]),
           _AWN_MATS.get(sh["awning"],M["awning_r"]),C_com)
    _box(f"com_path{{sh['y']:.0f}}",G1+2.5,sh["y"],0.04,5.0,3.5,0.05,M["stone_path"],C_com)

if SE_DELIVERY:
    print("[urban_pipeline] Building reference-grade delivery hub from live source ...")
    _delivery_root = UA.build_delivery_reference_row(
        C_com, include_site=False,
        origin=(SE_DELIVERY[0], SE_DELIVERY[1], 0.0),
        yaw=SE_DELIVERY[2], prefix="urban_delivery:")
    _delivery_root["c2w_zone"] = "SE"
    _delivery_root["c2w_instance_id"] = "commercial.delivery_hub.000"

if SE_BIKESTAT:
    _box("bike_pad",SE_BIKESTAT[0],SE_BIKESTAT[1],0.04,10.0,7.0,0.05,M["stone_path"],C_com)
    UA.place_bicycle_station((SE_BIKESTAT[0],SE_BIKESTAT[1]),C_com,yaw=SE_BIKESTAT[2])
if SE_PHONEBOOTH:
    UA.place_phonebooth((SE_PHONEBOOTH[0],SE_PHONEBOOTH[1]),C_com,yaw=SE_PHONEBOOTH[2])
if SE_KIOSK:
    UA.place_kiosk5((SE_KIOSK[0],SE_KIOSK[1]),C_com,yaw=SE_KIOSK[2],scale=SE_KIOSK[3])
for bx2_,by2_,byw_ in SE_BENCHES:
    UA.place_bench_classic((bx2_,by2_),C_furn,yaw=byw_)
for bx2_,by2_ in SE_BINS:
    UA.place_bin_domed((bx2_,by2_),C_furn)
print("[urban_pipeline] Commercial done.")

# ═══════════════════════════════════════════════════════════════════════════════
# VEHICLES
# ═══════════════════════════════════════════════════════════════════════════════
_VEH_EXCL=frozenset({{"CameraTarget","KeyLight","OrbitCamera","Camera","Light","Sun","Area"}})
CARS={{
    "bmw":     OX_BASE/"m1_bmw_x1_2016/m1_bmw_x1_2016.blend",
    "audi":    OX_BASE/"m1_audi_q7_2015/m1_audi_q7_2015.blend",
    "volvo":   OX_BASE/"m1_volvo_v60_polestar_2013/m1_volvo_v60_polestar_2013.blend",
    "mini":    OX_BASE/"m1_mini_countryman_2016/m1_mini_countryman_2016.blend",
    "hyundai": OX_BASE/"m1_hyundai_tucson_2015/m1_hyundai_tucson_2015.blend",
    "dacia":   OX_BASE/"m1_dacia_duster_2010/m1_dacia_duster_2010.blend",
    "fiat":    OX_BASE/"n1_fiat_ducato_2014/n1_fiat_ducato_2014.blend",
    "gmc":     OX_BASE/"n2_gmc_hummer_2021_pickup/n2_gmc_hummer_2021_pickup.blend",
}}
def place_car(tag,blend_path,at,C,yaw=0.0):
    bp=Path(blend_path)
    if not bp.exists(): print(f"[urban_pipeline] MISSING: {{bp}}"); return []
    with bpy.data.libraries.load(str(bp),link=False) as (src,dst):
        dst.objects=[n for n in src.objects if n not in _VEH_EXCL]
    root=None; objs=[]
    for o in dst.objects:
        if o is None: continue
        try: C.objects.link(o)
        except RuntimeError: pass
        objs.append(o)
        if o.name=="Grp_Root" and o.parent is None: root=o
    for o in objs: o.name=f"{{tag}}_{{o.name}}"
    if root is None:
        for o in objs:
            if o.parent is None and o.type=="EMPTY": root=o; break
    if root:
        root.location.x=at[0]; root.location.y=at[1]; root.location.z=0.0; root.rotation_euler.z=yaw
        root["c2w_dynamic_role"]="vehicle"; root["c2w_forward_axis"]="X"
    return objs

print("[urban_pipeline] Placing vehicles ...")
place_car("vn1",CARS["bmw"],    ( LC,20.0),C_cars,yaw= math.pi/2)
place_car("vn2",CARS["volvo"],  ( LC,34.0),C_cars,yaw= math.pi/2)
place_car("vn3",CARS["audi"],   (-LC,27.0),C_cars,yaw=-math.pi/2)
place_car("vs1",CARS["mini"],   ( LC,-18.0),C_cars,yaw=-math.pi/2)
place_car("vs2",CARS["hyundai"],(-LC,-14.0),C_cars,yaw= math.pi/2)
place_car("ve1",CARS["fiat"],   (22.0,-LC),C_cars,yaw=0)
place_car("ve2",CARS["dacia"],  (38.0,-LC),C_cars,yaw=0)
place_car("vw1",CARS["gmc"],    (-26.0,LC),C_cars,yaw=math.pi)
print("[urban_pipeline] Vehicles placed.")

# ═══════════════════════════════════════════════════════════════════════════════
# LIGHTING
# ═══════════════════════════════════════════════════════════════════════════════
bpy.context.scene.world=bpy.data.worlds.new("sky_up")
bpy.context.scene.world.use_nodes=True
wt=bpy.context.scene.world.node_tree; wt.nodes.clear()
bg=wt.nodes.new("ShaderNodeBackground"); sky=wt.nodes.new("ShaderNodeTexSky")
lp=wt.nodes.new("ShaderNodeLightPath"); mix=wt.nodes.new("ShaderNodeMixShader")
bg2=wt.nodes.new("ShaderNodeBackground"); out=wt.nodes.new("ShaderNodeOutputWorld")
sky.sky_type="NISHITA"
sky.sun_elevation=math.radians(SUN_ELEVATION_DEG)
sky.sun_rotation=math.radians(SUN_ROTATION_DEG)
sky.altitude=800.0; sky.air_density=1.0; sky.dust_density=0.4
bg.inputs["Strength"].default_value=1.0; bg2.inputs["Strength"].default_value=0.0
wt.links.new(sky.outputs["Color"],bg.inputs["Color"])
wt.links.new(lp.outputs["Is Camera Ray"],mix.inputs["Fac"])
wt.links.new(bg.outputs["Background"],mix.inputs[1])
wt.links.new(bg2.outputs["Background"],mix.inputs[2])
wt.links.new(mix.outputs["Shader"],out.inputs["Surface"])
bpy.ops.object.light_add(type="SUN",location=(20,-40,60))
sun=bpy.context.active_object; sun.name="Sun_up"
sun.data.energy=5.0; sun.data.angle=math.radians(0.5)
sun.rotation_euler[0]=math.radians(90-SUN_ELEVATION_DEG)
sun.rotation_euler[2]=math.radians(SUN_ROTATION_DEG)

# ─── RENDER + CAMERAS ────────────────────────────────────────────────────────
sc=bpy.context.scene
sc.render.engine="CYCLES"; sc.render.resolution_x=1920; sc.render.resolution_y=1080
sc.render.image_settings.file_format="PNG"
sc.cycles.samples=RENDER_SAMPLES; sc.cycles.use_denoising=True
try: sc.cycles.denoiser="OPTIX"
except:
    try: sc.cycles.denoiser="OPENIMAGEDENOISE"
    except: pass
sc.cycles.device="GPU"
try: sc.view_settings.view_transform="AgX"; sc.view_settings.exposure=-2.2; sc.view_settings.gamma=1.0
except Exception as e: print(f"[urban_pipeline] AgX: {{e}}")

def make_cam(name,loc,target,fov=58):
    bpy.ops.object.camera_add(location=loc)
    cam=bpy.context.active_object; cam.name=name; cam.data.name=name
    cam.data.lens_unit="FOV"; cam.data.angle=math.radians(fov)
    dv=Vector(target)-Vector(loc)
    if dv.length>0: cam.rotation_euler=dv.to_track_quat("-Z","Y").to_euler()
    return cam

cam_ov=make_cam("cam_overview",    (5,-75,95),   (0,10,0),  64)
cam_rs=make_cam("cam_residential", (15,5,28),    (-30,36,8),58)
cam_pk=make_cam("cam_park",        (-12,36,22),  (34,28,2), 62)
cam_cm=make_cam("cam_commercial",  (5,-5,20),    (32,-30,4),60)
cam_ix=make_cam("cam_intersection",(-20,-22,18), (0,0,0),   56)

bpy.ops.wm.save_as_mainfile(filepath=str(OUT/"urban_pipeline.blend"))
print("[urban_pipeline] Blend saved.")
for cam,fname in [(cam_ov,"overview.png"),(cam_rs,"residential.png"),
                  (cam_pk,"park.png"),(cam_cm,"commercial.png"),(cam_ix,"intersection.png")]:
    sc.camera=cam; sc.render.filepath=str(OUT/fname)
    print(f"[urban_pipeline] Rendering {{fname}} ...")
    bpy.ops.render.render(write_still=True)
    print(f"[urban_pipeline] Done: {{fname}}")
_ua_stats = UA.asset_stats()
_instances = [o for o in bpy.data.objects if o.get("c2w_role") == "instance"]
_masters = [o for o in bpy.data.objects if o.get("c2w_role") == "master"]
_streetlights = [o for o in _instances if "streetlight" in str(o.get("c2w_asset_id", ""))]
_window_objects = [o for o in bpy.data.objects if o.name.startswith("apt_w")]
_balcony_objects = [o for o in bpy.data.objects if o.name.startswith("apt_bs")]
_window_meshes = {{o.data.name for o in _window_objects if o.data}}
_balcony_meshes = {{o.data.name for o in _balcony_objects if o.data}}
_collection_instances = [o for o in _instances if o.instance_type == "COLLECTION"]
_validation = {{
    "passed": bool(_collection_instances) and len(_window_meshes) <= 1 and len(_balcony_meshes) <= 1,
    "collection_instances_present": bool(_collection_instances),
    "streetlight_instances": len(_streetlights),
    "streetlight_master_collections": len({{o.instance_collection.name for o in _streetlights if o.instance_collection}}),
    "apartment_window_objects": len(_window_objects),
    "apartment_window_meshes": len(_window_meshes),
    "apartment_balcony_objects": len(_balcony_objects),
    "apartment_balcony_meshes": len(_balcony_meshes),
    "instances_reference_master": all(
        o.data is not None or o.instance_collection is not None for o in _instances
    ),
}}
_stats = {{
    "objects_total": len(bpy.data.objects),
    "master_objects": len(_masters),
    "instance_objects": len(_instances),
    "unique_meshes": len(bpy.data.meshes),
    "materials": len(bpy.data.materials),
    "external_library_loads": _ua_stats["external_library_loads"],
    "prototype_collections": _ua_stats["prototype_collections"],
    "primitive_meshes": _ua_stats["primitive_meshes"],
    "build_seconds": round(time.perf_counter() - PIPELINE_STARTED, 3),
    "blend_file_size_bytes": (OUT/"urban_pipeline.blend").stat().st_size,
}}
(OUT/"asset_stats.json").write_text(json.dumps(_stats, indent=2), encoding="utf-8")
(OUT/"validation_report.json").write_text(json.dumps(_validation, indent=2), encoding="utf-8")
print("[urban_pipeline] All complete.")
'''
    return script


# ─── REALIZER CLASS ───────────────────────────────────────────────────────────
class UrbanRealizer:
    def __init__(self, api_key=None, base_url=None, model_name=None):
        config = get_llm_config(default_model=model_name)
        self.config = config
        self.client = make_openai_client(config, api_key=api_key, base_url=base_url)
        self.model_name = model_name or config.model

    def synthesize_gin(self, params, manifest_data=None, user_prompt=None):
        """Build gin config for the flat/legacy path (deterministic + optional LLM review)."""
        base_gin = build_gin_from_params(params, manifest_data)

        manifest_str = json.dumps(manifest_data, indent=2) if manifest_data else "{}"
        params_str = json.dumps(params, indent=2)
        user_section = (
            f"\n### ORIGINAL USER PROMPT:\n{user_prompt}\n\n" if user_prompt else ""
        )

        system_prompt = f"""
You are the **Urban Scene Realizer** (Agent 3) for WorldBridge.
A deterministic compiler produced the base gin file below.
Review and optionally enrich it — add comments, fix logical issues.
DO NOT invent new gin parameter names, remove lines, or add markdown.

{user_section}### BASE GIN FILE:
{base_gin}

### RESOLVED PARAMETERS (reference):
{params_str}

### URBAN MANIFEST (context):
{manifest_str}

### OUTPUT:
Return ONLY the final .gin file content. No markdown, no code blocks.
"""
        try:
            content = complete_text(
                self.client,
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {
                        "role": "user",
                        "content": "Output the final enriched urban .gin file.",
                    },
                ],
                temperature=0.05,
            )
            content = content.strip()
            if content.startswith("```gin") or content.startswith("```"):
                content = content.split("\n", 1)[1] if "\n" in content else content[3:]
            if content.endswith("```"):
                content = content[:-3]
            return content.strip()
        except Exception as e:
            print("API Error in Urban Realizer — falling back to deterministic gin:")
            print(describe_llm_exception(e))
            return base_gin


def save_gin(content, output_gin=OUTPUT_GIN, output_copy=OUTPUT_GIN_COPY):
    if not content:
        return False
    output_gin.parent.mkdir(parents=True, exist_ok=True)
    output_gin.write_text(content + "\n", encoding="utf-8")
    output_copy.parent.mkdir(parents=True, exist_ok=True)
    output_copy.write_text(content + "\n", encoding="utf-8")
    print(f"[Urban Realizer] Gin file saved to: {output_gin}")
    return True


def save_run_args():
    args = {"configs": ["base_urban", "generated_urban_scene"]}
    OUTPUT_RUN_ARGS.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_RUN_ARGS.write_text(json.dumps(args, indent=4), encoding="utf-8")
    print(f"[Urban Realizer] Run args saved to: {OUTPUT_RUN_ARGS}")
    return args


def main():
    user_prompt = sys.argv[1] if len(sys.argv) > 1 else ""

    if not INPUT_PARAMS.exists():
        print(f"Error: {INPUT_PARAMS} not found. Please run the Urban Resolver first.")
        sys.exit(1)

    params = json.loads(INPUT_PARAMS.read_text(encoding="utf-8"))
    print(f"[Urban Realizer] Read params from: {INPUT_PARAMS}")

    manifest_data = None
    if INPUT_MANIFEST.exists():
        manifest_data = json.loads(INPUT_MANIFEST.read_text(encoding="utf-8"))

    scene_type = params.get("scene_type", "flat")

    if scene_type == "crossroads_4zone":
        print("[Urban Realizer] Generating crossroads Blender script ...")
        script = build_crossroads_script(params)
        OUTPUT_SCENE_PY.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_SCENE_PY.write_text(script, encoding="utf-8")
        print(f"[Urban Realizer] Blender scene script saved to: {OUTPUT_SCENE_PY}")
        print("[Urban Realizer] Run with:")
        print(f"  blender --background --python {OUTPUT_SCENE_PY}")
        # Also write a minimal gin stub for tool compatibility
        gin_stub = "# crossroads_4zone scene — use urban_scene.py instead\n"
        save_gin(gin_stub)
        save_run_args()
    else:
        print("[Urban Realizer] Generating flat urban gin config ...")
        realizer = UrbanRealizer()
        gin_content = realizer.synthesize_gin(params, manifest_data, user_prompt)
        if not save_gin(gin_content):
            print("Error: Failed to save gin file.")
            sys.exit(1)
        run_args = save_run_args()
        print(f"[Urban Realizer] Use configs: {' '.join(run_args['configs'])}")


if __name__ == "__main__":
    main()
