import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from worldbridge.llm_config import complete_text, get_llm_config, make_openai_client

INPUT_STRATEGY = Path("./output/indoor/solver_scene_indoor.json")
OUTPUT_GIN = Path(
    "./infinigen/infinigen_examples/configs_indoor/generated_indoor_scene.gin"
)
OUTPUT_GIN_COPY = Path("./output/indoor/scene_indoor.gin")
OUTPUT_RUN_ARGS = Path("./output/indoor/indoor_run_args.json")

REF_SOURCE_PATH = Path("./infinigen/infinigen_examples/generate_indoors.py")
REF_GIN_PATHS = [
    Path("./infinigen/infinigen_examples/configs_indoor/base_indoors.gin"),
    Path("./infinigen/infinigen_examples/configs_indoor/fast_solve.gin"),
    Path("./infinigen/infinigen_examples/configs_indoor/singleroom.gin"),
    Path("./infinigen/infinigen_examples/configs_indoor/overhead.gin"),
    Path("./infinigen/infinigen_examples/configs_indoor/real_geometry.gin"),
    Path("./infinigen/infinigen_examples/configs_indoor/studio.gin"),
]

ALLOWED_BASE_CONFIGS = {
    "singleroom",
    "fast_solve",
    "overhead",
    "real_geometry",
    "studio",
}


class ModelingAgent:
    def __init__(self, api_key=None, base_url=None, model_name=None):
        config = get_llm_config(default_model=model_name)
        self.client = make_openai_client(config, api_key=api_key, base_url=base_url)
        self.model_name = model_name or config.model

    @staticmethod
    def read_file_content(path):
        if not path.exists():
            print(f"Warning: Reference file not found: {path}")
            return ""
        return path.read_text(encoding="utf-8")

    def read_gin_references(self):
        chunks = []
        for path in REF_GIN_PATHS:
            content = self.read_file_content(path)
            if content:
                chunks.append(f"### {path.name}\n{content}")
        return "\n\n".join(chunks)

    def run(self, strategy_json_data, source_code, gin_references):
        system_prompt = """
You are the Modeling Agent for Infinigen Indoor.
Your task is to convert a high-level Generation Strategy JSON into a valid `.gin` configuration text.

You have access to the exact parameter names from `generate_indoors.py` and indoor base configuration files.

DEFAULT CONFIGURATION VALUES:
1. Solver Steps:
   - Base values: Large=300, Medium=200, Small=50
   - Fast values: Large=100, Medium=40, Small=5
   - Valid variables:
     `compose_indoors.solve_steps_large`
     `compose_indoors.solve_steps_medium`
     `compose_indoors.solve_steps_small`

2. Room Restrictions:
   - `restrict_solving.restrict_parent_rooms` is a list of room tags.
   - `compose_indoors.restrict_single_supported_roomtype` is a boolean.
   - When specifying a room, set `restrict_solving.restrict_parent_rooms = ["RoomType"]`.

3. Visibility and Rendering:
   - `compose_indoors.invisible_room_ceilings_enabled`
   - `compose_indoors.terrain_enabled`
   - `set_displacement_mode.displacement_mode`

MAPPING RULES:
A. Room Restriction:
- If `restrict_room` is not null, output:
  `restrict_solving.restrict_parent_rooms = ["Kitchen"]`
  `compose_indoors.restrict_single_supported_roomtype = False`

B. Solver / Clutter Modes:
- "Minimalist" or "Empty":
  `compose_indoors.solve_steps_large = 10`
  `compose_indoors.solve_steps_medium = 5`
  `compose_indoors.solve_steps_small = 0`
- "Standard" or "Default":
  Omit solver-step overrides unless a fast/minimal setup is clearly selected.
- "Messy" or "HighClutter":
  `compose_indoors.solve_steps_large = 300`
  `compose_indoors.solve_steps_medium = 300`
  `compose_indoors.solve_steps_small = 200`

C. Ceiling Visibility:
- If `ceiling_visibility` is false, output `compose_indoors.invisible_room_ceilings_enabled = True`.
- If `ceiling_visibility` is true, output `compose_indoors.invisible_room_ceilings_enabled = False`.

D. Quality:
- If `quality_mode` is "HighQuality", output `set_displacement_mode.displacement_mode = "DISPLACEMENT"`.

E. Global Safety:
- Always output `compose_indoors.terrain_enabled = False` unless the strategy explicitly requests terrain.

OUTPUT REQUIREMENT:
- Return ONLY valid gin configuration text.
- Start with `# Generated by Indoor Modeling Agent`.
- Use Python-like lists for arrays.
- Do not use markdown blocks or explanations outside the gin file.
"""

        user_prompt = f"""
Generation Strategy:
{json.dumps(strategy_json_data, indent=2)}

Reference source excerpt:
{source_code[:60000]}

Reference indoor gin files:
{gin_references[:60000]}
"""

        print("[Indoor Modeling Agent] Generating gin configuration...")

        try:
            result = complete_text(
                self.client,
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.1,
            )
            result = result.strip()
            if result.startswith("```"):
                result = result.split("\n", 1)[1]
            if result.endswith("```"):
                result = result[:-3]
            return result.strip()
        except Exception as e:
            print(f"API Error in Indoor Modeling Agent: {e}")
            return None


def normalize_config_name(name):
    path = Path(str(name))
    return path.stem


def selected_configs(strategy_data):
    configs = []
    for item in strategy_data.get("selected_gin_files", []):
        name = normalize_config_name(item)
        if name in ALLOWED_BASE_CONFIGS and name not in configs:
            configs.append(name)

    if "generated_indoor_scene" not in configs:
        configs.append("generated_indoor_scene")
    return configs


def save_gin_file(content, output_path=OUTPUT_GIN):
    if not content:
        return False

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content + "\n", encoding="utf-8")

    OUTPUT_GIN_COPY.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_GIN_COPY.write_text(content + "\n", encoding="utf-8")
    print(f"Gin file saved to: {output_path}")
    return True


def save_run_args(strategy_data):
    data = {"configs": selected_configs(strategy_data)}
    OUTPUT_RUN_ARGS.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_RUN_ARGS.write_text(
        json.dumps(data, indent=4, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"Indoor run args saved to: {OUTPUT_RUN_ARGS}")
    return data


def main():
    if not INPUT_STRATEGY.exists():
        print(f"Error: {INPUT_STRATEGY} not found. Please run the indoor solver first.")
        raise SystemExit(1)

    strategy_data = json.loads(INPUT_STRATEGY.read_text(encoding="utf-8"))
    agent = ModelingAgent()
    source_code = agent.read_file_content(REF_SOURCE_PATH)
    gin_references = agent.read_gin_references()

    if not source_code:
        print("Error: Infinigen indoor source reference is missing.")
        raise SystemExit(1)

    gin_content = agent.run(strategy_data, source_code, gin_references)
    if not save_gin_file(gin_content):
        raise SystemExit(1)

    run_args = save_run_args(strategy_data)
    print(f"Use configs: {' '.join(run_args['configs'])}")


if __name__ == "__main__":
    main()
