"""Thirty new district compositions; all asset keys refer to existing models."""
from pathlib import Path

R = Path(__file__).resolve().parents[1]
O = R / "infinigen/outputs/outdoor_full_demo/urban_v1_full_connect4"
A = O / "shared_assets"
PREVIOUS = R / "infinigen/outputs/outdoor_full_demo/urban_v1_full_connect3"
CORE = {"restaurant", "cafe", "market", "hospital", "pharmacy", "library"}
ENTERABLE = CORE | {"bar", "corner_store", "police", "fire", "delivery", "gas"}
# key, title, focus, neighbouring buildings, urban form, landscape, services
SCENES = [
    (
        "orchard_market",
        "Fresh Fruit Street",
        "market",
        ["cafe", "corner_store", "townhouse"],
        "terraced",
        "orchard",
        ["parcel"],
    ),
    (
        "canal_dining",
        "Riverfront Dining District",
        "restaurant",
        ["bar", "cafe", "townhouse"],
        "canal",
        "river",
        ["bike"],
    ),
    (
        "coffee_garden",
        "Coffee Garden Street",
        "cafe",
        ["library", "restaurant", "townhouse"],
        "court",
        "garden",
        ["food_locker"],
    ),
    (
        "clinic_park",
        "Hospital Healing Garden",
        "hospital",
        ["pharmacy", "cafe", "townhouse"],
        "terraced",
        "garden",
        ["atm"],
    ),
    (
        "pharmacy_mews",
        "Pharmacy Residential Street",
        "pharmacy",
        ["market", "townhouse", "townhouse"],
        "mews",
        "orchard",
        ["parcel"],
    ),
    (
        "library_lake",
        "Pondside Library Street",
        "library",
        ["cafe", "school", "townhouse"],
        "crescent",
        "lake",
        ["bike"],
    ),
    (
        "seven_corner",
        "Corner Life Street 711",
        "corner_store",
        ["market", "cafe", "townhouse"],
        "corner",
        "garden",
        ["atm", "parcel"],
    ),
    (
        "bar_fountain",
        "water fountain bar square",
        "bar",
        ["restaurant", "cafe", "bank"],
        "court",
        "fountain",
        ["atm"],
    ),
    (
        "parcel_court",
        "courier service courtyard",
        "delivery",
        ["corner_store", "market", "townhouse"],
        "mews",
        "garden",
        ["parcel", "food_locker"],
    ),
    (
        "police_civic",
        "Police Department of Citizen's Neighborhood",
        "police",
        ["library", "cafe", "pharmacy"],
        "terraced",
        "fountain",
        ["atm"],
    ),
    (
        "fire_river",
        "Fire station Riverside district",
        "fire",
        ["delivery", "market", "cafe"],
        "canal",
        "river",
        ["parcel"],
    ),
    (
        "fuel_market",
        "Gas station and convenience lifestyle district",
        "gas",
        ["corner_store", "restaurant", "delivery"],
        "terraced",
        "garden",
        ["atm", "food_locker"],
    ),
    (
        "campus_reading",
        "Campus Reading Walkway",
        "library",
        ["school", "gym", "cafe"],
        "court",
        "garden",
        ["bike", "fitness"],
    ),
    (
        "sports_dining",
        "Sports and Dining Park",
        "restaurant",
        ["gym", "school", "market"],
        "corner",
        "fountain",
        ["fitness", "fitness_walk"],
    ),
    (
        "family_grove",
        "Urban Forest Green Living Circle",
        "corner_store",
        ["townhouse", "townhouse", "cafe", "pharmacy"],
        "mews",
        "orchard",
        ["parcel"],
    ),
    (
        "health_lake",
        "Medical Lakeside Neighborhood",
        "pharmacy",
        ["hospital", "library", "cafe"],
        "crescent",
        "lake",
        ["fitness_walk"],
    ),
    (
        "factory_services",
        "factory support zone",
        "delivery",
        ["factory", "restaurant", "corner_store"],
        "terraced",
        "garden",
        ["food_locker", "parcel"],
    ),
    (
        "bank_promenade",
        "Bank Green Walk Street",
        "cafe",
        ["bank", "pharmacy", "corner_store"],
        "promenade",
        "fountain",
        ["atm"],
    ),
    (
        "fresh_waterfront",
        "Waterfront Fresh Market",
        "market",
        ["restaurant", "bar", "townhouse"],
        "canal",
        "river",
        ["bike"],
    ),
    (
        "neighborhood_bistro",
        "neighborhood restaurant courtyard",
        "restaurant",
        ["townhouse", "corner_store", "cafe"],
        "court",
        "orchard",
        ["food_locker"],
    ),
    (
        "emergency_square",
        "Emergency Medical Services at the Service Square",
        "police",
        ["fire", "hospital", "pharmacy"],
        "terraced",
        "garden",
        ["atm"],
    ),
    (
        "reading_residences",
        "Reading Garden for Residential Area",
        "library",
        ["townhouse", "townhouse", "corner_store"],
        "mews",
        "fountain",
        ["parcel", "fitness"],
    ),
    (
        "coffee_canal",
        "River Café & Art Bar",
        "cafe",
        ["bar", "library", "corner_store"],
        "canal",
        "river",
        ["bike"],
    ),
    (
        "clinic_courtyard",
        "Medical Convenience Garden",
        "hospital",
        ["pharmacy", "delivery", "market"],
        "court",
        "garden",
        ["parcel", "food_locker"],
    ),
    (
        "seven_lake",
        "711 Lakefront Living Street",
        "corner_store",
        ["cafe", "restaurant", "townhouse"],
        "crescent",
        "lake",
        ["fitness", "atm"],
    ),
    (
        "bar_reading_lane",
        "Green Street Bookstore on Green Street Bar",
        "bar",
        ["library", "cafe", "townhouse"],
        "promenade",
        "orchard",
        ["bike"],
    ),
    (
        "fire_industrial",
        "Fire and Industry Services District",
        "fire",
        ["factory", "delivery", "gas"],
        "terraced",
        "garden",
        ["food_locker"],
    ),
    (
        "fuel_greenway",
        "Green Station Oasis",
        "gas",
        ["cafe", "market", "townhouse"],
        "promenade",
        "garden",
        ["parcel", "fitness_walk"],
    ),
    (
        "market_fountain",
        "FreshSprinkler Life Square",
        "market",
        ["pharmacy", "corner_store", "restaurant"],
        "court",
        "fountain",
        ["atm", "parcel"],
    ),
    (
        "delivery_lakeside",
        "Lakeview Express Community",
        "delivery",
        ["townhouse", "corner_store", "cafe", "library"],
        "crescent",
        "lake",
        ["parcel", "food_locker"],
    ),
]
assert len(SCENES) == 30 and len({s[0] for s in SCENES}) == 30
