"""
Build urban_v3_all35 by refining the existing urban_v3_all34 blend in place.

Task: add ONE house in the residential area (west side of the north arm),
facing the road, appropriately sized — using infinigen's OWN indoor procedural
generation pipeline for the building itself.

The house is generated by `infinigen_examples.generate_indoors` (coarse task,
fast_solve config, terrain/backdrop disabled) into
`infinigen/outputs/urban_v3_all35_house/coarse/scene.blend`. If that fresh
generation is unavailable, we fall back to the already-pipeline-generated house
in `infinigen/outputs/indoor2/coarse/scene.blend` (also a generate_indoors
coarse output). Either way the building comes from infinigen's indoor pipeline.

We append only the building + furniture collection ("unique_assets", which
nests the exterior walls / roof / windows / doors, plus "skirting" and
"door_base_elements*"), skipping terrain / cameras / coarse placeholders, then
place + orient + scale the whole house into the residential yard facing +X.
"""

# Allow direct execution as well as package imports.
import sys as _wb_sys
from pathlib import Path as _WBPath

_wb_root = next(
    p for p in _WBPath(__file__).resolve().parents if (p / "worldbridge").is_dir()
)
if str(_wb_root) not in _wb_sys.path:
    _wb_sys.path.insert(0, str(_wb_root))
from worldbridge.paths import path_variables as _wb_path_variables

_wb_paths = _wb_path_variables()

_wb_WORLDBRIDGE_ROOT = _wb_paths["WORLDBRIDGE_ROOT"]


from pathlib import Path
import math
import sys

import bpy
from mathutils import Vector

ROOT = Path(f"{_wb_WORLDBRIDGE_ROOT}")
SRC_BLEND = ROOT / "infinigen/outputs/urban_v3_all34/urban_v3_all34.blend"
FRESH_HOUSE = ROOT / "infinigen/outputs/urban_v3_all35_house/coarse/scene.blend"
FALLBACK_HOUSE = ROOT / "infinigen/outputs/indoor2/coarse/scene.blend"
OUT = ROOT / "infinigen/outputs/urban_v3_all35"
OUT.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(ROOT / "scripts"))

# placement: west side of the north (residential) arm, facade facing +X (road)
TARGET_FRONT_X = -10.5  # east (road-facing) wall sits here, 2.5 m off the sidewalk
TARGET_CY = 31.0  # centred up the north arm
MAX_FACADE = 20.0  # cap the road-facing width
MAX_DEPTH = 15.0  # cap the yard depth

WANT = lambda c: (
    c == "unique_assets" or c == "skirting" or c.startswith("door_base_elements")
)

# ─────────────────────────────────────────────────────────────────────────────
print(f"[all35] Opening base blend: {SRC_BLEND}", flush=True)
bpy.ops.wm.open_mainfile(filepath=str(SRC_BLEND))
print(f"[all35] Opened. objects={len(bpy.data.objects)}", flush=True)

bpy.context.scene.render.engine = "CYCLES"
try:
    prefs = bpy.context.preferences.addons["cycles"].preferences
    prefs.compute_device_type = "OPTIX"
    prefs.get_devices()
    for d in prefs.devices:
        d.use = True
    bpy.context.scene.cycles.device = "GPU"
    print("[all35] GPU: OPTIX", flush=True)
except Exception as _e:
    print(f"[all35] OPTIX: {_e}", flush=True)
    try:
        prefs = bpy.context.preferences.addons["cycles"].preferences
        prefs.compute_device_type = "CUDA"
        prefs.get_devices()
        for d in prefs.devices:
            d.use = True
        bpy.context.scene.cycles.device = "GPU"
        print("[all35] GPU: CUDA", flush=True)
    except Exception as _e2:
        print(f"[all35] CUDA: {_e2}", flush=True)


# ═════════════════════════════════════════════════════════════════════════════
# IMPORT THE INFINIGEN HOUSE (building + furniture collections only)
# ═════════════════════════════════════════════════════════════════════════════
def import_house(src):
    with bpy.data.libraries.load(str(src), link=False) as (s, d):
        d.collections = [c for c in s.collections if WANT(c)]
    colls = [c for c in d.collections if c is not None]
    objs = set()
    for c in colls:
        for o in c.all_objects:
            objs.add(o)
    return colls, objs


house_src = FRESH_HOUSE if FRESH_HOUSE.exists() else FALLBACK_HOUSE
print(f"[all35] Importing house from: {house_src}", flush=True)
colls, house_objs = import_house(house_src)
mesh_n = len([o for o in house_objs if o.type == "MESH"])
if mesh_n < 20 and house_src != FALLBACK_HOUSE:
    print(
        f"[all35]   fresh house too small ({mesh_n} meshes) — using fallback",
        flush=True,
    )
    house_src = FALLBACK_HOUSE
    colls, house_objs = import_house(house_src)
    mesh_n = len([o for o in house_objs if o.type == "MESH"])
print(
    f"[all35]   imported {len(house_objs)} house objects ({mesh_n} meshes) from {house_src.parent.parent.name}",
    flush=True,
)

# link house objects into a new in-scene collection so they render
House = bpy.data.collections.new("House_indoor")
bpy.context.scene.collection.children.link(House)
for o in house_objs:
    try:
        House.objects.link(o)
    except RuntimeError:
        pass


# ── group under an empty and transform into place ─────────────────────────────
def house_world_bbox(objs):
    mn = [1e18, 1e18, 1e18]
    mx = [-1e18, -1e18, -1e18]
    for o in objs:
        if o.type != "MESH":
            continue
        for c in o.bound_box:
            w = o.matrix_world @ Vector(c)
            for i in range(3):
                mn[i] = min(mn[i], w[i])
                mx[i] = max(mx[i], w[i])
    return mn, mx


mn, mx = house_world_bbox(house_objs)
dx, dy = mx[0] - mn[0], mx[1] - mn[1]
print(
    f"[all35]   native footprint dx={dx:.2f} dy={dy:.2f} dz={mx[2]-mn[2]:.2f}",
    flush=True,
)

# orient so the LONGER horizontal side is the road-facing facade (along Y)
rot_z = math.pi / 2 if dx > dy else 0.0
facade_w = max(dx, dy)
depth = min(dx, dy)
scale = min(1.0, MAX_FACADE / facade_w, MAX_DEPTH / depth)
print(
    f"[all35]   rot_z={rot_z:.2f} facade_w={facade_w:.2f} depth={depth:.2f} scale={scale:.3f}",
    flush=True,
)

empty = bpy.data.objects.new("House_root", None)
bpy.context.scene.collection.objects.link(empty)
for o in house_objs:
    if o.parent is None or o.parent not in house_objs:
        o.parent = empty
        o.matrix_parent_inverse = empty.matrix_world.inverted()

empty.rotation_euler.z = rot_z
empty.scale = (scale, scale, scale)
bpy.context.view_layer.update()

# measure post-transform bbox, then translate so (max_x, center_y, min_z) lands
# at (TARGET_FRONT_X, TARGET_CY, 0)
mn2, mx2 = house_world_bbox(house_objs)
anchor = (mx2[0], (mn2[1] + mx2[1]) / 2.0, mn2[2])
empty.location.x += TARGET_FRONT_X - anchor[0]
empty.location.y += TARGET_CY - anchor[1]
empty.location.z += 0.0 - anchor[2]
bpy.context.view_layer.update()
mn3, mx3 = house_world_bbox(house_objs)
print(
    f"[all35]   placed house: X[{mn3[0]:.1f},{mx3[0]:.1f}] Y[{mn3[1]:.1f},{mx3[1]:.1f}] Z[{mn3[2]:.1f},{mx3[2]:.1f}]",
    flush=True,
)


# ═════════════════════════════════════════════════════════════════════════════
# SAVE + RENDER
# ═════════════════════════════════════════════════════════════════════════════
out_blend = OUT / "urban_v3_all35.blend"
print(f"[all35] Saving blend -> {out_blend}", flush=True)
bpy.ops.wm.save_as_mainfile(filepath=str(out_blend))
print("[all35] Blend saved.", flush=True)

sc = bpy.context.scene
RENDERS = [
    ("cam_overview", "overview.png"),
    ("cam_residential", "residential.png"),
    ("cam_park", "park.png"),
    ("cam_commercial", "commercial.png"),
    ("cam_intersection", "intersection.png"),
]
for cam_name, fname in RENDERS:
    cam = bpy.data.objects.get(cam_name)
    if cam is None:
        print(f"[all35] MISSING camera {cam_name}, skipping {fname}", flush=True)
        continue
    sc.camera = cam
    sc.render.filepath = str(OUT / fname)
    print(f"[all35] Rendering {fname} ...", flush=True)
    bpy.ops.render.render(write_still=True)
    print(f"[all35] Done: {fname}", flush=True)

print("[all35] ALL DONE.", flush=True)
