"""Connected production build of the full-scene urban agent4 mission.

This stage is reachable only through ``generate_urban_v1_full_07.py`` with
``C2W_AGENT4_UPGRADE=1``.  It verifies the audited 5 GB river3 checkpoint,
executes the source module that creates the physical doorway, stairs, robot,
route and cameras, then saves a complete production blend in the requested
agent4 output directory.
"""
from __future__ import annotations

# Allow direct execution as well as package imports.
import sys as _wb_sys
from pathlib import Path as _WBPath

_wb_root = next(
    p for p in _WBPath(__file__).resolve().parents if (p / "worldbridge").is_dir()
)
if str(_wb_root) not in _wb_sys.path:
    _wb_sys.path.insert(0, str(_wb_root))
from worldbridge.paths import path_variables as _wb_path_variables

_wb_paths = _wb_path_variables()

_wb_WORLDBRIDGE_ROOT = _wb_paths["WORLDBRIDGE_ROOT"]


import json
import os
import sys
import time
from pathlib import Path

import bpy

ROOT = Path(f"{_wb_WORLDBRIDGE_ROOT}")
sys.path.insert(0, str(ROOT / "scripts"))
import urban_v1_full_07_agent_mission  # noqa: E402


BASE_OUT = ROOT / "infinigen/outputs/outdoor_full_demo/urban_v1_full_07-river3"
BASE_BLEND = BASE_OUT / "urban_v1_full_07-river3.blend"
BASE_AUDIT = BASE_OUT / "generation_audit.json"
OUT = (
    ROOT
    / "infinigen/outputs/outdoor_full_demo"
    / os.environ.get("C2W_OUTPUT_REVISION", "urban_v1_full_07_agent4")
)
BLEND = OUT / f"{OUT.name}.blend"


def _log(message: str) -> None:
    line = f"[Agent4ProductionUpgrade] {message}"
    print(line, flush=True)
    with (OUT / "generation.log").open("a", encoding="utf8") as handle:
        handle.write(line + "\n")


def _write_readme(mission: dict) -> None:
    collision = mission["collision_audit"]
    robot = mission["robot"]
    text = f"""# Urban v1 full 07 — Agent4 production mission

This directory is generated from the complete audited
`urban_v1_full_07-river3` production checkpoint through the real
`generate_urban_v1_full_07.py` pipeline.  It is not an overlay-only blend,
compact preview, proxy massing scene, or toy model.

The complete city, river, vegetation, traffic, detailed Infinigen residential
interior, zebra crossings and detailed Fresh Mart are preserved.  The large
house receives a boolean-cut front-door opening aligned to the real 1.455 m
interior floor, a detailed animated door, and nine supported exterior treads.
A {robot['mesh_part_count']}-part articulated humanoid travels from the bedroom,
through that opening, along the residential sidewalk, across the west zebra
crossing, and through the clear parking aisle to Fresh Mart.
Its 22 mm first-person camera is mounted 0.42 m along the travel direction,
clear of the detailed sensor head shell, and the third-person chase remains wide.

Collision audit: **{'PASS' if collision['passed'] else 'FAIL'}**

- safety radius: {collision['robot_safety_radius_m']:.2f} m
- route samples: {collision['route_sample_count']}
- evaluated radial rays: {collision['radial_rays_cast']}
- door clearance rays: {collision['door_clearance_ray_count']}
- support keys: {collision['support_key_count']}

Primary files:

- `{BLEND.name}` — complete production scene and animation
- `mission_manifest.json` — route, door, robot, cameras and quality audit
- `collision_audit.json` — detailed no-collision/no-penetration audit
- `generation_audit.json` — verified real-generator lineage
- PNG stills and first/third-person MP4 files generated by the connected
  agent4 render stage
- `contact_sheet_16_views.jpg` — quick 4x4 overview of the complete route
"""
    (OUT / "README.md").write_text(text, encoding="utf8")


def main() -> None:
    started = time.time()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "generation.log").write_text("", encoding="utf8")
    loaded = Path(bpy.data.filepath).resolve() if bpy.data.filepath else None
    if loaded != BASE_BLEND.resolve():
        raise RuntimeError(
            f"agent4 upgrade must load the verified river3 checkpoint {BASE_BLEND}; loaded={loaded}"
        )
    if not BASE_AUDIT.is_file():
        raise RuntimeError(f"river3 production audit missing: {BASE_AUDIT}")
    report = json.loads(BASE_AUDIT.read_text(encoding="utf8"))
    toy = report.get("toy_model_audit", {})
    if (
        not report.get("source_level_generation")
        or not report.get("river3_source_level_generation")
        or not toy.get("river3_no_toy_or_degenerate_models")
        or report.get("output") != str(BASE_BLEND)
    ):
        raise RuntimeError(
            "agent4 refused an unaudited, incomplete, or non-production river3 checkpoint"
        )

    _log(
        f"Verified complete river3 checkpoint: scene_objects={len(bpy.context.scene.objects)}, "
        f"data_objects={len(bpy.data.objects)}, collections={len(bpy.data.collections)}"
    )
    mission = urban_v1_full_07_agent_mission.build()
    if (
        not mission["collision_audit"]["passed"]
        or not mission["quality_audit"]["valid"]
    ):
        raise RuntimeError("agent4 mission failed its mandatory collision/quality gate")

    scene = bpy.context.scene
    scene["c2w_revision"] = OUT.name
    scene["c2w_base_revision"] = "urban_v1_full_07-river3"
    scene["c2w_generator"] = os.environ.get(
        "C2W_GENERATOR_ENTRY", str(Path(__file__).resolve())
    )
    scene["c2w_agent4_checkpoint_upgrade"] = True
    scene["c2w_agent4_complete_production_scene"] = True
    scene["c2w_agent4_render_source"] = str(BLEND)

    chain = list(report.get("real_generator_chain", []))
    chain.append(
        "generate_urban_v1_full_07.py -> upgrade_urban_v1_full_07_agent4.py -> "
        "urban_v1_full_07_agent_mission.build (physical door/stair, detailed humanoid, "
        "collision-audited route and wide cameras in complete river3 city)"
    )
    base_validation_renders = list(report.get("renders", []))
    report.update(
        {
            "output": str(BLEND),
            "generator_entry": scene["c2w_generator"],
            "source_level_generation": True,
            "agent4_source_level_generation": True,
            "production_checkpoint_reused": str(BASE_BLEND),
            "production_checkpoint_audit": str(BASE_AUDIT),
            "old_regional_blends_loaded": False,
            "real_generator_chain": chain,
            "base_river3_validation_renders": base_validation_renders,
            "renders": [],
            "render_files_complete": False,
            "agent4_mission": mission,
            "elapsed_seconds": round(time.time() - started, 2),
        }
    )
    updated_toy = dict(toy)
    updated_toy.update(
        {
            "agent4_complete_scene_preserved": True,
            "agent4_no_proxy_or_compact_scene": True,
            "agent4_no_toy_or_degenerate_models": mission["quality_audit"]["valid"],
            "agent4_mission_mesh_count": mission["quality_audit"][
                "mission_mesh_object_count"
            ],
            "agent4_robot_mesh_part_count": mission["robot"]["mesh_part_count"],
            "agent4_robot_authored_vertex_count": mission["robot"][
                "authored_mesh_vertex_count"
            ],
            "policy": (
                "preserve complete audited river3 production city; reject proxy, compact, toy and "
                "degenerate mission geometry; require physical doorway and collision-audited route"
            ),
        }
    )
    report["toy_model_audit"] = updated_toy
    requirement = dict(report.get("requirement_audit", {}))
    requirement.update(
        {
            "complete_complex_scene_preserved": True,
            "real_generator_modified_and_connected": True,
            "real_door_passage": not mission["collision_audit"]["door_blockers"],
            "collision_and_penetration_free_route": mission["collision_audit"][
                "passed"
            ],
            "bedroom_to_zebra_to_store_route": True,
            "wide_first_person_camera": True,
            "wide_third_person_camera": True,
            "complete_route_aerial_camera": True,
            "no_toy_or_degenerate_models": mission["quality_audit"]["valid"],
        }
    )
    report["requirement_audit"] = requirement

    manifest = {
        "title": "Complete-production-city humanoid mission: bedroom to Fresh Mart",
        "source_blend": str(BASE_BLEND),
        "output_blend": str(BLEND),
        "source_modified": False,
        "generator_entry": scene["c2w_generator"],
        "production_stage": str(Path(__file__).resolve()),
        "complete_scene_preserved": True,
        "proxy_or_compact_scene_created": False,
        **mission,
        "render_plan": {
            "stills": "16 wide views rendered from the complete output blend",
            "videos": ["first_person_ultrawide", "third_person_wide"],
            "authorized_gpus": [2, 5],
        },
    }
    (OUT / "mission_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf8"
    )
    (OUT / "collision_audit.json").write_text(
        json.dumps(mission["collision_audit"], indent=2, ensure_ascii=False),
        encoding="utf8",
    )
    (OUT / "generation_audit.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf8"
    )
    _write_readme(mission)

    _log(
        f"Mission gates passed: samples={mission['collision_audit']['route_sample_count']}, "
        f"rays={mission['collision_audit']['radial_rays_cast']}, "
        f"robot_parts={mission['robot']['mesh_part_count']}"
    )
    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND), compress=True)
    _log(
        f"Saved complete agent4 production scene: {BLEND}; "
        f"elapsed={time.time() - started:.1f}s"
    )


if __name__ == "__main__":
    main()
