"""Source-level third residential district for ``urban_v1_full_09``.

The visible architecture is generated by the active ALL45-09 procedural
building functions in the same Blender process.  No completed residential
Blend is opened or appended.  The district retains ALL45-09's three low-rise
and eight high-rise dense-courtyard organization, facade language, spacing and
native-scale exterior dimensions, while reusing the five botanical tree
masters generated earlier in the full-city run.

The site is placed north of the two retained FULL07 residential areas.  A
pair of separated one-way community streets connects the existing y=65.5 m
street to the new east/west street without demolishing the retained houses or
apartments.  Markings, stop bars and pedestrian crossings are source geometry
and are audited here rather than painted into a saved scene.
"""
from __future__ import annotations

# Allow direct execution as well as package imports.
import sys as _wb_sys
from pathlib import Path as _WBPath

_wb_root = next(
    p for p in _WBPath(__file__).resolve().parents if (p / "worldbridge").is_dir()
)
if str(_wb_root) not in _wb_sys.path:
    _wb_sys.path.insert(0, str(_wb_root))
from worldbridge.paths import path_variables as _wb_path_variables

_wb_paths = _wb_path_variables()

_wb_WORLDBRIDGE_ROOT = _wb_paths["WORLDBRIDGE_ROOT"]


import copy
import importlib.util
import json
import math
import random
from pathlib import Path

import bpy
from mathutils import Vector


ROOT = Path(f"{_wb_WORLDBRIDGE_ROOT}")
PREFIX = "full09_res:"
DISTRICT_OFFSET = Vector((-22.0, 182.0, 0.0))
NEW_STREET_Y = 182.0 - 108.0 * 0.43
RIVER_RESERVE_WEST_X = 56.5
_ALL45_09_SOURCE = None


def _load_all45_09_source():
    global _ALL45_09_SOURCE
    if _ALL45_09_SOURCE is None:
        path = ROOT / "scripts/generate_urban_v3_all45_03.py"
        spec = importlib.util.spec_from_file_location("full09_all45_09_source", path)
        module = importlib.util.module_from_spec(spec)
        assert spec.loader is not None
        spec.loader.exec_module(module)
        _ALL45_09_SOURCE = module
    module = _ALL45_09_SOURCE
    module.ROOT = ROOT
    module.OUT = ROOT / "infinigen/outputs/outdoor_full_demo/urban_v1_full_09"
    module.PREFIX = PREFIX
    module.P.ROOT = ROOT
    module.P.OUT = module.OUT
    module.P.PREFIX = PREFIX
    module.P.RNG = random.Random(4509)
    module.P.G.ROOT = ROOT
    module.P.G.OUT = module.OUT
    module.P.G.PREFIX = PREFIX
    module.P.G.RNG = random.Random(4509)
    return module


def preload_source() -> str:
    """Freeze the active ALL45-09 source module at full-city process start."""
    return str(Path(_load_all45_09_source().__file__).resolve())


def _tree_masters() -> list[bpy.types.Collection]:
    masters = sorted(
        [
            c
            for c in bpy.data.collections
            if c.name.startswith("full02:MASTER:TreeFactory:")
        ],
        key=lambda collection: collection.name,
    )
    if len(masters) < 5:
        raise RuntimeError(
            f"FULL09 requires five same-run botanical tree masters; got {len(masters)}"
        )
    for master in masters[:5]:
        if (
            int(master.get("c2w_explicit_leaf_count", 0)) < 3000
            or int(master.get("c2w_botanical_branch_count", 0)) < 300
            or not master.get("c2w_no_blob_or_topiary_geometry")
        ):
            raise RuntimeError(
                f"FULL09 rejected non-production tree master {master.name}"
            )
    return masters[:5]


def _world_bounds(objects) -> tuple[Vector, Vector]:
    points = [
        obj.matrix_world @ Vector(corner) for obj in objects for corner in obj.bound_box
    ]
    if not points:
        raise RuntimeError("FULL09 residential district has no boundable geometry")
    return (
        Vector(tuple(min(point[axis] for point in points) for axis in range(3))),
        Vector(tuple(max(point[axis] for point in points) for axis in range(3))),
    )


def _build_lowrise(R, item, index, config, materials, assets, root):
    design = R.lowrise_design(index, config)
    collection = R.P.add_house_exterior(
        item["name"], design, item["origin"], item["yaw"], materials, assets, root
    )
    front = -design["d"] / 2
    for x in (-design["w"] / 2 + 0.22, design["w"] / 2 - 0.22):
        R.P.G.local_box(
            f"{item['name']}_expressionist_pier_{x:.2f}",
            item["origin"],
            item["yaw"],
            (x, front - 0.36, 3.15),
            (0.42, 0.58, 6.10),
            materials["copper_patina"],
            collection,
            bevel=0.025,
            segments=3,
        )
    collection["building_type"] = "all45_09_native_scale_lowrise_exterior"
    collection["facade_style"] = config["facade"]["style"]
    collection["interiors_generated"] = False
    collection["c2w_no_completed_residential_blend_loaded"] = True
    collection[
        "c2w_exterior_source"
    ] = "generate_urban_v3_all45_03.py:lowrise_design + add_house_exterior"
    return collection


def _marking_material(R):
    return R.P.remap_material(
        "full09_traffic_marking",
        (0.63, 0.60, 0.49),
        (0.96, 0.94, 0.82),
        0.62,
        0.015,
        13.0,
    )


def _yellow_material(R):
    return R.P.remap_material(
        "full09_traffic_yellow",
        (0.52, 0.34, 0.018),
        (0.96, 0.70, 0.075),
        0.58,
        0.015,
        11.0,
    )


def _arrow(R, name, x, y, direction, material, collection):
    sign = 1.0 if direction == "north" else -1.0
    stem = R.P.G.box(
        name + "_stem",
        (x, y - sign * 0.48, 0.245),
        (0.20, 1.24, 0.018),
        material,
        collection,
        bevel=0.008,
    )
    points = [
        (x, y + sign * 0.95),
        (x - 0.46, y + sign * 0.25),
        (x + 0.46, y + sign * 0.25),
    ]
    head = R.P.G.poly_prism(
        name + "_head", points, 0.238, 0.022, material, collection, bevel=0.008
    )
    for obj in (stem, head):
        obj["c2w_marking_type"] = "direction_arrow"
        obj["c2w_lane_direction"] = direction
    return [stem, head]


def _build_connected_streets(R, materials, root) -> dict:
    import urban_assets as UA

    roads = R.P.G.make_collection("full09_connected_residential_streets", root)
    marking = _marking_material(R)
    yellow = _yellow_material(R)
    asphalt = materials["asphalt"]
    paving = materials["pale_paver"]

    # Two 4.4 m one-way carriageways leave a landscaped/pedestrian median and
    # clear all five retained FULL07 buildings by more than two metres.
    south_y, north_y = 65.5, NEW_STREET_Y - 6.0
    length = north_y - south_y
    center_y = (south_y + north_y) / 2
    carriageways = []
    for x, direction in ((-11.0, "south"), (11.0, "north")):
        road = R.P.G.box(
            f"{direction}bound_community_carriageway",
            (x, center_y, 0.125),
            (4.4, length, 0.10),
            asphalt,
            roads,
            bevel=0.055,
        )
        road["c2w_road_class"] = "separated_one_way_residential_connector"
        road["c2w_lane_direction"] = direction
        road["c2w_lane_width_m"] = 4.4
        carriageways.append(road)
        for arrow_y in (84.0, 108.0):
            _arrow(
                R,
                f"{direction}bound_direction_arrow_{int(arrow_y)}",
                x,
                arrow_y,
                direction,
                marking,
                roads,
            )
        # A solid edge line on each side preserves the central pedestrian
        # median and prevents the one-way pair from reading as an unmarked lot.
        for side in (-1, 1):
            edge = R.P.G.box(
                f"{direction}bound_edge_line_{side:+d}",
                (x + side * 2.02, center_y, 0.242),
                (0.10, length - 1.0, 0.018),
                marking,
                roads,
                bevel=0.004,
            )
            edge["c2w_marking_type"] = "lane_edge_line"
            edge["c2w_lane_direction"] = direction

    # Real pedestrian construction runs beside the carriageways and keeps the
    # original central garden path intact as a traffic-free median.
    for x, side in ((-14.35, "west"), (14.35, "east")):
        path = R.P.G.box(
            f"connector_sidewalk_{side}",
            (x, center_y, 0.205),
            (1.55, length, 0.12),
            paving,
            roads,
            bevel=0.04,
        )
        path["c2w_role"] = "continuous_accessible_residential_sidewalk"

    # Stop control where the separated pair meets the new 12 m east/west
    # street.  Southbound traffic stops before entering the retained district;
    # northbound traffic has a receiving-lane arrow and a yield line.
    stop_bars = []
    for x, control in ((-11.0, "STOP"), (11.0, "YIELD")):
        bar = R.P.G.box(
            f"{control.lower()}_bar_at_new_street",
            (x, north_y - 0.55, 0.25),
            (3.65, 0.28, 0.022),
            marking,
            roads,
            bevel=0.006,
        )
        bar["c2w_marking_type"] = "stop_or_yield_bar"
        bar["c2w_control"] = control
        stop_bars.append(bar)

    # Zebra crossing aligned with ALL45-09's north/south shared mews.  It spans
    # the complete 12 m road and is kept distinct from the inherited nine-stripe
    # FULL08 crossing so both can be audited independently.
    crosswalks = []
    for index, x in enumerate([-25.2 + 0.8 * i for i in range(9)]):
        stripe = R.P.G.box(
            f"third_district_zebra_{index:02d}",
            (x, NEW_STREET_Y, 0.245),
            (0.43, 11.0, 0.020),
            marking,
            roads,
            bevel=0.010,
        )
        stripe["c2w_marking_type"] = "full09_zebra_crosswalk"
        stripe["c2w_crossing_axis"] = "north_south"
        stripe["c2w_connects_road_sides"] = True
        stripe["c2w_cross_road_span_m"] = 11.0
        crosswalks.append(stripe)

    # 3 m / 3 m broken yellow centre line on the new street.  Dashes are
    # suppressed at the crosswalk and both connector junction conflict boxes.
    dashes = []
    cursor = -91.0
    while cursor + 3.0 <= 52.0:
        center_x = cursor + 1.5
        in_exclusion = any(
            abs(center_x - value) < radius
            for value, radius in ((-22, 5.3), (-11, 5.0), (11, 5.0))
        )
        if not in_exclusion:
            dash = R.P.G.box(
                f"new_street_center_dash_{len(dashes):02d}",
                (center_x, NEW_STREET_Y, 0.242),
                (3.0, 0.12, 0.018),
                yellow,
                roads,
                bevel=0.004,
            )
            dash["c2w_marking_type"] = "full09_centerline"
            dash["c2w_line_style"] = "dashed"
            dash["c2w_conflict_area_clear"] = True
            dashes.append(dash)
        cursor += 6.0

    streetlights = 0
    for y in (78.0, 95.0, 112.0, 126.0):
        UA.place_streetlight((-15.45, y), roads, yaw=0, day=True)
        UA.place_streetlight((15.45, y), roads, yaw=math.pi, day=True)
        streetlights += 2

    return {
        "valid": True,
        "carriageway_count": len(carriageways),
        "one_way_directions": sorted(
            road["c2w_lane_direction"] for road in carriageways
        ),
        "lane_width_m": 4.4,
        "sidewalk_count": 2,
        "direction_arrow_objects": 8,
        "stop_or_yield_bars": len(stop_bars),
        "third_district_zebra_stripes": len(crosswalks),
        "third_district_zebra_span_m": 11.0,
        "new_street_center_dashes": len(dashes),
        "streetlights": streetlights,
        "intersection_exclusion_centers_x": [-22.0, -11.0, 11.0],
        "connector_y_range_m": [south_y, north_y],
        "new_east_west_street_center_y_m": NEW_STREET_Y,
        "reference_blends_loaded": [],
    }


def build() -> dict:
    R = _load_all45_09_source()
    config = copy.deepcopy(R.DEFAULT_CONFIG)
    config["landscape"]["shrubs_per_bed"] = 0
    config["landscape"]["flowers_per_bed"] = 0
    config["landscape"]["grass_per_bed"] = 0
    config["lowrise"]["interiors"] = "source_level_exterior_only_in_full_city"
    R.PREFIX = PREFIX
    R.P.PREFIX = PREFIX
    R.P.G.PREFIX = PREFIX
    R.P.RNG = random.Random(4509)
    R.P.G.RNG = random.Random(4509)

    root = R.P.G.make_collection("third_residential_all45_09_source_rebuild")
    root["c2w_semantic_zone"] = "third northern residential district"
    root["c2w_source_generator"] = str(ROOT / "scripts/generate_urban_v3_all45_03.py")
    root["c2w_reference_revision"] = "urban_v3_all45_09"
    root["c2w_completed_regional_blends_loaded"] = False
    root["c2w_layout_offset_m"] = list(DISTRICT_OFFSET)

    materials = R.make_materials(config)
    R.P.G.MATS = materials
    assets = R.make_assets(materials)
    trees = _tree_masters()
    for index, master in enumerate(trees):
        assets[f"native_tree_{index}"] = master
    # ALL45-09 deliberately disables every small ground-cover master.  Keep
    # all three keys explicit because the active source landscape routine
    # audits the master count even when a placement count is zero.
    assets["native_shrub_count"] = 0
    assets["native_flower_count"] = 0
    assets["native_grass_count"] = 0

    low_layout, high_layout = R.generate_layout(config)
    clearance = R.layout_clearance_audit(low_layout, high_layout, config)
    if (
        len(low_layout) != 3
        or len(high_layout) != 8
        or clearance["minimum_highrise_to_highrise_m"] <= 12.0
    ):
        raise RuntimeError(f"FULL09 rejected ALL45-09 layout: {clearance}")

    landscape = R.add_site_and_native_landscape(config, materials, assets, root)
    lowrise_collections = [
        _build_lowrise(R, item, index, config, materials, assets, root)
        for index, item in enumerate(low_layout)
    ]
    rng = random.Random(int(config["seed"]) + 17)
    floor_lo, floor_hi = map(int, config["highrise"]["floor_range"])
    towers = []
    tower_stats = []
    for index, item in enumerate(high_layout):
        collection, stats = R.add_tower(
            item["name"],
            item["origin"],
            item["yaw"],
            rng.randint(floor_lo, floor_hi),
            index,
            config,
            materials,
            assets,
            root,
        )
        collection["c2w_source_reference"] = "urban_v3_all45_09 highrise generator"
        towers.append(collection)
        tower_stats.append(stats)

    # Translate only the linked district graph.  Unlinked reusable masters stay
    # in local coordinates and therefore instance correctly after translation.
    district_objects = list(root.all_objects)
    for obj in district_objects:
        obj.location += DISTRICT_OFFSET

    roads = _build_connected_streets(R, materials, root)

    visible_meshes = [
        obj for obj in root.all_objects if obj.type == "MESH" and not obj.hide_render
    ]
    minimum, maximum = _world_bounds(visible_meshes)
    river_clearance = RIVER_RESERVE_WEST_X - maximum.x
    if river_clearance < 3.0:
        raise RuntimeError(
            f"FULL09 third residential district encroaches on river reserve: clearance={river_clearance:.3f}m"
        )
    if landscape["shrubs"] or landscape["flowers"] or landscape["grass"]:
        raise RuntimeError(
            f"FULL09 forbids coarse/floating residential ground cover: {landscape}"
        )

    forbidden = ("toy", "placeholder", "proxy", "dummy", "lowpoly")
    forbidden_visible = [
        obj.name
        for obj in root.all_objects
        if not obj.hide_render and any(token in obj.name.lower() for token in forbidden)
    ]
    if forbidden_visible:
        raise RuntimeError(
            f"FULL09 residential no-toy audit failed: {forbidden_visible[:20]}"
        )

    audit = {
        "valid": True,
        "reference_revision": "urban_v3_all45_09",
        "source_generator": str(ROOT / "scripts/generate_urban_v3_all45_03.py"),
        "source_level_generation": True,
        "completed_residential_blends_loaded": False,
        "reference_blends_loaded": [],
        "layout_mode": config["layout"]["mode"],
        "facade_style": config["facade"]["style"],
        "building_count": len(lowrise_collections) + len(towers),
        "lowrise_count": len(lowrise_collections),
        "highrise_count": len(towers),
        "highrise_floor_counts": [item["floors"] for item in tower_stats],
        "layout_clearances": clearance,
        "district_offset_m": list(DISTRICT_OFFSET),
        "world_bounds_min_m": [round(float(value), 3) for value in minimum],
        "world_bounds_max_m": [round(float(value), 3) for value in maximum],
        "river_reserve_clearance_m": round(float(river_clearance), 3),
        "same_run_botanical_tree_masters": [master.name for master in trees],
        "landscape": landscape,
        "connected_street_system": roads,
        "interior_policy": (
            "full-city integration regenerates ALL45-09 native-scale exteriors; completed Indoor/"
            "regional Blend files are not appended"
        ),
        "forbidden_visible_object_names": forbidden_visible,
        "no_toy_or_degenerate_models": True,
    }
    root["c2w_full09_residential_audit"] = json.dumps(audit, sort_keys=True)
    bpy.context.scene["c2w_full09_third_residential_valid"] = True
    return audit
