#!/usr/bin/env python3
"""Validate and index the ordinary residential/retail GLM connect2 deliverable."""

from __future__ import annotations

# Resolve the checkout independently of this method package's depth.
import sys as _baseline_sys
from pathlib import Path as _BaselinePath

_BASELINE_PROJECT_ROOT = next(
    p
    for p in _BaselinePath(__file__).resolve().parents
    if (p / "worldbridge").is_dir() and (p / "baselines/registry.py").is_file()
)
if str(_BASELINE_PROJECT_ROOT) not in _baseline_sys.path:
    _baseline_sys.path.insert(0, str(_BASELINE_PROJECT_ROOT))


from pathlib import Path
import sys

sys.path.insert(0, str((_BASELINE_PROJECT_ROOT / "baselines/tools")))
import baselines.methods.glm_flash.tools.validate_glm_flash_connect as base


OUTPUT = base.BASELINES / "annotations/glm53_flash/connect2"
SCENES = (
    "apartment_living_room",
    "suburban_kitchen_dining",
    "townhouse_entry_lounge",
    "neighborhood_bakery",
    "corner_convenience_store",
    "small_clothing_boutique",
)


def main() -> int:
    base.OUTPUT = OUTPUT
    base.SCENES = SCENES
    result = base.main()
    readme = """# GLM-5.3 Flash connect2: ordinary residential and retail scenes

This directory contains six genuine Blender 3D indoor/outdoor environments in
one shared coordinate frame per scene. The set intentionally uses ordinary,
recognizable programs rather than stylized destination spaces:

- apartment living/dining room and balcony/courtyard
- family kitchen/dining room and backyard patio
- townhouse entry/lounge and front porch/street
- neighborhood bakery and sidewalk
- corner convenience store and neighborhood street
- small clothing boutique and pedestrian retail frontage

Every scene contains editable `scene/scene.blend`, exported `scene/scene.glb`,
sixteen separate unlabelled 1280x720 PNG images, and two 960x540 H.264 videos.
Twelve of the sixteen stills are varied far, middle, oblique and elevated views
through the indoor/outdoor opening. The two five-second videos traverse the same
physical open entrance in opposite directions at 24 fps (120 frames each).

Interior detail is constructed from multi-part procedural assemblies: cabinet
carcasses/fronts/handles, appliances, upholstered furniture, shelves with many
individual products, clothing racks and garments, lights, trim, plants and small
accessories. Materials use procedural color and micro-bump variation; no external
textures or scene assets were downloaded.

Blueprint source was generated by `glm-5.3-flash` through the GLM Coding Plan
endpoint. The API secret was process-only and is not stored. Rendering used
Blender 4.5.4 EEVEE Next on CPU because the NVIDIA driver was unavailable.
See `VALIDATION_REPORT.json` for hashes, media probes and per-image statistics.
"""
    (OUTPUT / "README.md").write_text(readme, encoding="utf-8")
    return result


if __name__ == "__main__":
    raise SystemExit(main())
